import { useEffect, useRef, useState, type FormEvent } from 'react';
import { BarChart3, Eye, FileInput, Leaf, Search, Trash2, TrendingUp } from 'lucide-react';
import { listStockInIngredients, type StockInIngredient } from '../../services/ingredients';
import { listInventoryBatches, type InventoryBatch } from '../../services/inventory-batches';
import { createUsageRecord, getUsageSummary, listUsageRecords, type UsageRecord, type UsageSummary } from '../../services/usage-records';
import { createWasteRecord, getWasteSummary, listWasteRecords, type WasteReason, type WasteRecord, type WasteSummary } from '../../services/waste-records';
import { formatDateTime, localDateInputValue } from '../../utils/date-time';
import { Dialog } from './Dialog';
import { ApplicationPendingState } from './ApplicationPatterns';
import { DataState, PageHeader, Pagination } from './primitives';

const PAGE_SIZES = [10, 15, 50, 100, 150] as const;
const WASTE_REASONS: WasteReason[] = ['Expired', 'Spoiled', 'Damaged', 'Over-prepared', 'Other'];
type CombinedRecord = { id: string; createdAt: string; ingredient: { name: string }; batch: { batchID: string }; type: 'Usage' | 'Waste'; quantity: number; unit: string; notes: string; recordedBy: { name: string } };

export function ConnectedManagerUsageWastePage() {
  const usageTrigger = useRef<HTMLButtonElement>(null); const wasteTrigger = useRef<HTMLButtonElement>(null);
  const [records, setRecords] = useState<CombinedRecord[] | null>(null); const [usageSummary, setUsageSummary] = useState<UsageSummary | null>(null); const [wasteSummary, setWasteSummary] = useState<WasteSummary | null>(null); const [failed, setFailed] = useState(false);
  const [ingredients, setIngredients] = useState<StockInIngredient[]>([]); const [batches, setBatches] = useState<InventoryBatch[]>([]);
  const [search, setSearch] = useState(''); const [range, setRange] = useState('All dates'); const [from, setFrom] = useState(''); const [to, setTo] = useState(''); const [category, setCategory] = useState(''); const [ingredientFilter, setIngredientFilter] = useState(''); const [page, setPage] = useState(1); const [rows, setRows] = useState(10);
  const [detail, setDetail] = useState<CombinedRecord | null>(null);
  const [usageOpen, setUsageOpen] = useState(false); const [wasteOpen, setWasteOpen] = useState(false); const [busy, setBusy] = useState(false); const [message, setMessage] = useState('');
  const [transaction, setTransaction] = useState({ ingredientId: '', batchId: '', quantity: '', date: localDateInputValue(new Date()), reason: '' });
  const load = (signal?: AbortSignal) => Promise.all([listUsageRecords({ page: 1, pageSize: 150 }, signal), listWasteRecords({ page: 1, pageSize: 150 }, signal), getUsageSummary(signal), getWasteSummary(signal), listStockInIngredients(signal)])
    .then(([usage, waste, nextUsageSummary, nextWasteSummary, options]) => {
      const combined: CombinedRecord[] = [
        ...usage.items.map((item: UsageRecord) => ({ id: `usage-${item.id}`, createdAt: item.createdAt, ingredient: item.ingredient, batch: item.batch, type: 'Usage' as const, quantity: item.quantityUsed, unit: item.unit, notes: 'Usage recorded', recordedBy: item.recordedBy })),
        ...waste.items.map((item: WasteRecord) => ({ id: `waste-${item.id}`, createdAt: item.createdAt, ingredient: item.ingredient, batch: item.batch, type: 'Waste' as const, quantity: item.quantityWasted, unit: item.unit, notes: item.reason, recordedBy: item.recordedBy })),
      ].sort((a, b) => Date.parse(b.createdAt) - Date.parse(a.createdAt));
      setRecords(combined); setUsageSummary(nextUsageSummary); setWasteSummary(nextWasteSummary); setIngredients(options.ingredients); setFailed(false);
    }).catch(error => { if ((error as Error).name !== 'AbortError') setFailed(true); });
  useEffect(() => { const controller = new AbortController(); void load(controller.signal); return () => controller.abort(); }, []);
  useEffect(() => { if (!transaction.ingredientId) { setBatches([]); return; } const controller = new AbortController(); listInventoryBatches({ page: 1, pageSize: 150, ingredientId: transaction.ingredientId }, controller.signal).then(result => setBatches(result.items)).catch(() => setBatches([])); return () => controller.abort(); }, [transaction.ingredientId]);
  const openForm = (kind: 'usage' | 'waste') => { setTransaction({ ingredientId: '', batchId: '', quantity: '', date: localDateInputValue(new Date()), reason: '' }); setMessage(''); kind === 'usage' ? setUsageOpen(true) : setWasteOpen(true); };
  const submit = (kind: 'usage' | 'waste') => async (event: FormEvent) => {
    event.preventDefault(); setMessage(''); const quantity = Number(transaction.quantity);
    if (!transaction.ingredientId || !transaction.batchId || !transaction.date || !Number.isFinite(quantity) || quantity <= 0 || kind === 'waste' && !transaction.reason) { setMessage('Complete all required fields with a quantity greater than 0.'); return; }
    setBusy(true);
    try { if (kind === 'usage') await createUsageRecord({ ingredientId: transaction.ingredientId, batchId: transaction.batchId, dateUsed: transaction.date, quantityUsed: quantity }); else await createWasteRecord({ ingredientId: transaction.ingredientId, batchId: transaction.batchId, dateWasted: transaction.date, quantityWasted: quantity, reason: transaction.reason as WasteReason }); setUsageOpen(false); setWasteOpen(false); await load(); } catch { setMessage('Unable to save this transaction.'); } finally { setBusy(false); }
  };
  const dateMatches = (value: string) => { const day = value.slice(0, 10); if (range === 'Custom range') return (!from || day >= from) && (!to || day <= to); if (range === 'Today') return day === localDateInputValue(new Date()); const days = range === 'Last 7 Days' ? 7 : range === 'Last 30 Days' ? 30 : 0; return !days || Date.parse(value) >= Date.now() - days * 86400000; };
  const filtered = (records ?? []).filter(record => (!search || `${record.ingredient.name} ${record.batch.batchID}`.toLowerCase().includes(search.toLowerCase())) && (!ingredientFilter || record.ingredient.name === ingredientFilter) && dateMatches(record.createdAt));
  const pageRecords = filtered.slice((page - 1) * rows, page * rows);
  const totalUsage = usageSummary?.totalUsageToday ? `${usageSummary.totalUsageToday.quantity} ${usageSummary.totalUsageToday.unit}` : usageSummary?.usageRecordsToday === 0 ? '0' : '—';
  const totalWaste = wasteSummary?.totalWasteToday ? `${wasteSummary.totalWasteToday.quantity} ${wasteSummary.totalWasteToday.unit}` : wasteSummary?.wasteRecordsToday === 0 ? '0' : '—';
  const reset = () => { setSearch(''); setRange('All dates'); setFrom(''); setTo(''); setCategory(''); setIngredientFilter(''); setPage(1); };
  const TransactionFields = ({ waste }: { waste?: boolean }) => <div className="sl-form-grid"><label><span>Ingredient</span><select value={transaction.ingredientId} onChange={event => setTransaction(value => ({ ...value, ingredientId: event.target.value, batchId: '' }))}><option value="">Select ingredient</option>{ingredients.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label><span>Batch ID</span><select value={transaction.batchId} disabled={!transaction.ingredientId} onChange={event => setTransaction(value => ({ ...value, batchId: event.target.value }))}><option value="">Select batch ID</option>{batches.filter(item => item.quantity > 0).map(item => <option key={item.id} value={item.id}>{item.batchID}</option>)}</select></label><label><span>{waste ? 'Quantity Wasted' : 'Quantity Used'}</span><input inputMode="decimal" value={transaction.quantity} onChange={event => setTransaction(value => ({ ...value, quantity: event.target.value }))}/></label><label><span>Unit</span><output>{batches.find(item => item.id === transaction.batchId)?.unit ?? '—'}</output></label><label><span>{waste ? 'Date Wasted' : 'Date Used'}</span><input type="date" max={localDateInputValue(new Date())} value={transaction.date} onChange={event => setTransaction(value => ({ ...value, date: event.target.value }))}/></label>{waste && <label><span>Reason</span><select value={transaction.reason} onChange={event => setTransaction(value => ({ ...value, reason: event.target.value }))}><option value="">Select reason</option>{WASTE_REASONS.map(item => <option key={item}>{item}</option>)}</select></label>}</div>;

  return <><PageHeader eyebrow="Operations" title="Usage & Waste" description="Monitor ingredient usage and waste to identify trends, reduce losses, and improve efficiency." actions={<><button ref={usageTrigger} className="sl-button" type="button" onClick={() => openForm('usage')}>Record Usage</button><button ref={wasteTrigger} className="sl-button sl-button-primary" type="button" onClick={() => openForm('waste')}>Record Waste</button></>} />
    <div className="sl-admin-view sl-manager-usage-waste-v121 sl-manager-usage-live"><section className="sl-sa-kpis sl-manager-usage-kpis sl-kpi-reference-v201"><article className="sl-sa-kpi" data-tone="brand"><span className="sl-sa-kpi-icon"><Leaf /></span><div><span>Total Ingredients Used</span><strong>{failed ? '—' : totalUsage}</strong><small>{failed ? 'Usage data unavailable' : 'Usage quantity recorded today'}</small></div></article><article className="sl-sa-kpi" data-tone="info"><span className="sl-sa-kpi-icon"><Trash2 /></span><div><span>Total Waste</span><strong>{failed ? '—' : totalWaste}</strong><small>{failed ? 'Waste data unavailable' : 'Waste quantity recorded today'}</small></div></article><article className="sl-sa-kpi" data-tone="attention"><span className="sl-sa-kpi-icon"><BarChart3 /></span><div><span>Waste Rate</span><strong>—</strong><small>Compatible-unit metric pending</small></div></article><article className="sl-sa-kpi" data-tone="critical"><span className="sl-sa-kpi-icon"><TrendingUp /></span><div><span>Estimated Cost of Waste</span><strong>{wasteSummary ? `₱${wasteSummary.totalWasteCostToday.toFixed(2)}` : '—'}</strong><small>{failed ? 'Waste-cost data unavailable' : 'Waste cost recorded today'}</small></div></article></section>
      <section className="sl-manager-usage-filters"><label><span>Date Range</span><select value={range} onChange={event => { setRange(event.target.value); setPage(1); }}><option>All dates</option><option>Today</option><option>Last 7 Days</option><option>Last 30 Days</option><option>Custom range</option></select></label>{range === 'Custom range' && <div className="sl-v219-custom-date-range"><label><span>From</span><input type="date" value={from} onChange={event => setFrom(event.target.value)}/></label><label><span>To</span><input type="date" value={to} onChange={event => setTo(event.target.value)}/></label></div>}<label><span>Ingredient Category</span><select value={category} onChange={event => setCategory(event.target.value)}><option value="">All Categories</option></select></label><label><span>Ingredient</span><select value={ingredientFilter} onChange={event => { setIngredientFilter(event.target.value); setPage(1); }}><option value="">All Ingredients</option>{ingredients.map(item => <option key={item.id}>{item.name}</option>)}</select></label><div className="sl-manager-usage-filter-actions"><button className="sl-button" type="button" onClick={reset}>Reset</button></div></section>
      <div className="sl-manager-usage-analytics"><section className="sl-card"><header className="sl-card-header"><h2 className="sl-card-title">Usage vs Waste</h2></header><div className="sl-card-body"><ApplicationPendingState description="Usage and waste trends will appear when historical analytics are available." /></div></section><section className="sl-card"><header className="sl-card-header"><h2 className="sl-card-title">Waste by Reason</h2></header><div className="sl-card-body"><ApplicationPendingState description="Waste-reason analytics will appear when aggregated data is available." /></div></section><section className="sl-card"><header className="sl-card-header"><h2 className="sl-card-title">Top Ingredients by Waste</h2></header><div className="sl-card-body"><ApplicationPendingState description="Ingredient waste rankings will appear when analytics are available." /></div></section></div>
      <section className="sl-manager-usage-records sl-reference-records"><header><div><span className="sl-staff-usage-head-icon"><FileInput /></span><strong>Usage &amp; Waste Records</strong></div></header><div className="sl-manager-usage-record-toolbar"><label><span>Search records</span><span className="sl-directory-search"><Search size={16}/><input value={search} onChange={event => { setSearch(event.target.value); setPage(1); }} placeholder="Search by ingredient or Batch ID..."/></span></label></div><div className="sl-manager-usage-table-shell"><table className="sl-data-table sl-reference-records-table"><thead><tr>{['Date','Ingredient','Type','Quantity','Related Batch','Reason / Notes','Recorded By','Actions'].map(value => <th key={value}>{value}</th>)}</tr></thead><tbody>{pageRecords.length ? pageRecords.map(record => <tr key={record.id}><td>{formatDateTime(record.createdAt)}</td><td className="sl-emphasized-value">{record.ingredient.name}</td><td>{record.type}</td><td>{record.quantity} {record.unit}</td><td>{record.batch.batchID}</td><td>{record.notes}</td><td>{record.recordedBy.name}</td><td><button type="button" className="sl-icon-button" aria-label={`View ${record.type.toLowerCase()} record`} onClick={() => setDetail(record)}><Eye size={16}/></button></td></tr>) : <tr><td colSpan={8} className="sl-empty-cell"><DataState kind={failed ? 'error' : records === null ? 'loading' : 'empty'} title={failed ? 'Records unavailable' : records === null ? 'Loading records' : search || range !== 'All dates' || ingredientFilter ? 'No matching records' : 'No live records yet'} description={failed ? 'Usage and waste records could not be loaded.' : records === null ? 'Retrieving operational transactions.' : 'Usage and waste records will appear here after transactions are recorded.'}/></td></tr>}</tbody></table></div><footer className="sl-reference-records-footer"><label>Rows per page <select value={rows} onChange={event => { setRows(Number(event.target.value)); setPage(1); }}>{PAGE_SIZES.map(value => <option key={value}>{value}</option>)}</select></label><Pagination compact page={page} pageSize={rows} total={filtered.length} itemLabel="usage and waste records" onPageChange={setPage}/></footer></section>
    </div>
    <Dialog open={usageOpen} showClose={false} busy={busy} title="Record Usage" onDismiss={() => setUsageOpen(false)} returnFocus={usageTrigger} actions={<><button className="sl-button" type="button" onClick={() => setUsageOpen(false)}>Cancel</button><button className="sl-button sl-button-primary" type="submit" form="manager-record-usage">Save Usage Record</button></>}><form id="manager-record-usage" className="sl-manager-operation-form" onSubmit={submit('usage')}>{message && <p className="sl-inline-notice sl-inline-notice-error">{message}</p>}<TransactionFields /></form></Dialog>
    <Dialog open={wasteOpen} showClose={false} busy={busy} title="Record Waste" onDismiss={() => setWasteOpen(false)} returnFocus={wasteTrigger} actions={<><button className="sl-button" type="button" onClick={() => setWasteOpen(false)}>Cancel</button><button className="sl-button sl-button-primary" type="submit" form="manager-record-waste">Save Waste Record</button></>}><form id="manager-record-waste" className="sl-manager-operation-form" onSubmit={submit('waste')}>{message && <p className="sl-inline-notice sl-inline-notice-error">{message}</p>}<TransactionFields waste /></form></Dialog>
    <Dialog open={detail !== null} showClose={false} title={`${detail?.type ?? ''} Record Details`} onDismiss={() => setDetail(null)} actions={<button className="sl-button" type="button" onClick={() => setDetail(null)}>Close</button>}><dl className="sl-manager-detail-grid"><div><dt>Ingredient</dt><dd className="sl-emphasized-value">{detail?.ingredient.name}</dd></div><div><dt>Batch ID</dt><dd>{detail?.batch.batchID}</dd></div><div><dt>Date &amp; Time</dt><dd>{detail ? formatDateTime(detail.createdAt) : '—'}</dd></div><div><dt>Quantity</dt><dd>{detail ? `${detail.quantity} ${detail.unit}` : '—'}</dd></div><div><dt>Reason / Notes</dt><dd>{detail?.notes}</dd></div><div><dt>Recorded By</dt><dd>{detail?.recordedBy.name}</dd></div></dl></Dialog>
  </>;
}
