import { useEffect, useRef, useState } from 'react';
import { AlertTriangle, CalendarDays, CheckCircle2, Clock3, FileInput, FileText, Search } from 'lucide-react';
import { approveChangeRequest, getChangeRequest, listChangeRequests, rejectChangeRequest, type ChangeRequest, type ChangeRequestStatus, type ChangeRequestType } from '../../services/change-requests';
import { formatDateTime } from '../../utils/date-time';
import { formatHumanReadableText } from '../../utils/display-text';
import { Dialog } from './Dialog';
import { DataState, PageHeader, Pagination, Status } from './primitives';

const PAGE_SIZES = [10, 15, 50, 100, 150] as const;
const TYPES: Record<ChangeRequestType, string> = { BATCH_CORRECTION: 'Batch Correction', QUANTITY_ADJUSTMENT: 'Quantity Adjustment', UNIT_CORRECTION: 'Unit Correction', ADD_MISSING_BATCH: 'Add Missing Batch', OTHER: 'Other' };
const dateInput = (date: Date) => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`;

export function ConnectedManagerChangeRequestsPage() {
  const reviewTrigger = useRef<HTMLButtonElement>(null);
  const [search, setSearch] = useState(''); const [type, setType] = useState<ChangeRequestType | ''>(''); const [status, setStatus] = useState<ChangeRequestStatus | ''>(''); const [range, setRange] = useState('Last 30 Days'); const [from, setFrom] = useState(''); const [to, setTo] = useState(''); const [page, setPage] = useState(1); const [rows, setRows] = useState(10);
  const [data, setData] = useState<{ items: ChangeRequest[]; total: number } | null>(null); const [counts, setCounts] = useState<{ total: number; pending: number; approved: number; rejected: number } | null>(null); const [failed, setFailed] = useState(false); const [selected, setSelected] = useState<ChangeRequest | null>(null); const [confirming, setConfirming] = useState<'approve' | 'reject' | null>(null); const [reviewNote, setReviewNote] = useState(''); const [reviewError, setReviewError] = useState(''); const [busy, setBusy] = useState(false);
  const dates = () => { if (range === 'Custom') return { from: from || undefined, to: to || undefined }; const days = range === 'Last 7 Days' ? 7 : range === 'Last 90 Days' ? 90 : 30; const start = new Date(); start.setDate(start.getDate() - days + 1); return { from: dateInput(start), to: dateInput(new Date()) }; };
  const monthDates = () => { const start = new Date(); start.setDate(1); return { from: dateInput(start), to: dateInput(new Date()) }; };
  const load = (signal?: AbortSignal) => Promise.all([
    listChangeRequests({ page, pageSize: rows, search: search.trim() || undefined, type: type || undefined, status: status || undefined, ...dates() }, signal),
    listChangeRequests({ page: 1, pageSize: 10, ...dates() }, signal), listChangeRequests({ page: 1, pageSize: 10, status: 'PENDING', ...dates() }, signal), listChangeRequests({ page: 1, pageSize: 10, status: 'APPROVED', ...monthDates() }, signal), listChangeRequests({ page: 1, pageSize: 10, status: 'REJECTED', ...monthDates() }, signal),
  ]).then(([records, total, pending, approved, rejected]) => { setData(records); setCounts({ total: total.total, pending: pending.total, approved: approved.total, rejected: rejected.total }); setFailed(false); }).catch(error => { if ((error as Error).name !== 'AbortError') setFailed(true); });
  useEffect(() => { const controller = new AbortController(); const timeout = window.setTimeout(() => void load(controller.signal), 200); return () => { window.clearTimeout(timeout); controller.abort(); }; }, [search, type, status, range, from, to, page, rows]);
  const openReview = async (record: ChangeRequest, trigger: HTMLButtonElement) => { reviewTrigger.current = trigger; try { setSelected(await getChangeRequest(record.id)); } catch { setSelected(record); } };
  const decide = async () => { if (!selected || !confirming) return; if (confirming === 'reject' && !reviewNote.trim()) { setReviewError('Enter a rejection reason.'); return; } setBusy(true); setReviewError(''); try { if (confirming === 'approve') await approveChangeRequest(selected.id); else await rejectChangeRequest(selected.id, reviewNote.trim()); setConfirming(null); setSelected(null); setReviewNote(''); await load(); } catch { setReviewError('Unable to record this decision.'); } finally { setBusy(false); } };
  const statusLabel = (value: ChangeRequestStatus) => value === 'PENDING' ? 'Pending Review' : value === 'APPROVED' ? 'Approved' : 'Rejected';
  const detailRows = (record: ChangeRequest) => {
    const common: [string, string][] = [['Request ID', record.requestID], ['Submitted By', record.requestedBy.name], ['Submitted At', formatDateTime(record.createdAt)], ['Ingredient / Batch', [record.ingredient?.name, record.batch?.batchID].filter(Boolean).join(' · ') || '—']];
    if (record.requestType === 'QUANTITY_ADJUSTMENT') return [...common, ['Current Quantity', `${record.currentValue ?? '—'} ${record.batch?.unit ?? ''}`.trim()], ['Requested Quantity', `${record.requestedQuantity ?? '—'} ${record.batch?.unit ?? ''}`.trim()], ['Unit', record.batch?.unit ?? '—'], ['Reason', record.reason]];
    if (record.requestType === 'UNIT_CORRECTION') return [...common, ['Current Unit', record.currentValue ?? '—'], ['Requested Unit', record.requestedUnit ?? '—'], ['Reason', record.reason]];
    if (record.requestType === 'ADD_MISSING_BATCH') return [...common, ['Date Received', record.proposedBatch?.dateReceived ?? '—'], ['Quantity Received', String(record.proposedBatch?.quantityReceived ?? '—')], ['Expiration Date', record.proposedBatch?.expirationDate ?? '—'], ['Unit Cost', record.proposedBatch?.unitCost === undefined ? '—' : String(record.proposedBatch.unitCost)], ['Reason', record.reason]];
    if (record.requestType === 'OTHER') return [...common, ['Inventory Target', record.ingredient?.name ?? '—'], ['Request Description', record.requestDescription ?? '—'], ['Reason', record.reason]];
    return [...common, ['Detail to Correct', record.targetField ?? '—'], ['Current Value', record.currentValue ?? '—'], ['Requested Value', record.requestedValue ?? '—'], ['Reason', record.reason]];
  };
  const reset = () => { setSearch(''); setType(''); setStatus(''); setRange('Last 30 Days'); setFrom(''); setTo(''); setPage(1); };
  return <><PageHeader eyebrow="Operations" title="Change Requests" description="Review and decide on inventory-related requests submitted by your team." />
    <div className="sl-admin-view sl-mgr-cr-page sl-manager-change-requests-live"><section className="sl-sa-kpis sl-dashboard-source-kpis sl-kpi-reference-v201"><article className="sl-sa-kpi" data-tone="brand"><span className="sl-sa-kpi-icon"><FileInput/></span><div><span>Total Requests</span><strong>{counts?.total ?? '—'}</strong><small>{failed ? 'Request data unavailable' : counts ? 'Requests in the selected period' : 'Loading request summary'}</small></div></article><article className="sl-sa-kpi" data-tone="info"><span className="sl-sa-kpi-icon"><Clock3/></span><div><span>Pending Review</span><strong>{counts?.pending ?? '—'}</strong><small>{failed ? 'Request data unavailable' : counts ? 'Requires your action' : 'Loading request summary'}</small></div></article><article className="sl-sa-kpi" data-tone="attention"><span className="sl-sa-kpi-icon"><CheckCircle2/></span><div><span>Approved This Month</span><strong>{counts?.approved ?? '—'}</strong><small>{failed ? 'Request data unavailable' : counts ? 'Approval decisions recorded' : 'Loading request summary'}</small></div></article><article className="sl-sa-kpi" data-tone="critical"><span className="sl-sa-kpi-icon"><AlertTriangle/></span><div><span>Rejected This Month</span><strong>{counts?.rejected ?? '—'}</strong><small>{failed ? 'Request data unavailable' : counts ? 'Rejection decisions recorded' : 'Loading request summary'}</small></div></article></section>
      <section className="sl-mgr-cr-listcard sl-manager-request-records sl-application-records sl-sa-ingredients-table-card sl-sa-account-pattern-records"><header className="sl-application-records-header sl-staff-usage-card-head"><span className="sl-staff-usage-head-icon"><FileText/></span><h2>Change Request Records</h2></header><div className="sl-application-records-filters sl-sa-ingredients-table-filters"><div className="sl-application-records-toolbar sl-sa-ingredients-filter-card sl-mgr-cr-filters" data-filter-layout="records-five"><label className="search sl-application-records-search sl-sa-ingredients-search"><span>Search</span><span><Search size={17}/><input value={search} onChange={event => { setSearch(event.target.value); setPage(1); }} placeholder="Search requests..."/></span></label><label><span>Request Type</span><select value={type} onChange={event => { setType(event.target.value as ChangeRequestType | ''); setPage(1); }}><option value="">All Types</option>{Object.entries(TYPES).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label><span>Status</span><select value={status} onChange={event => { setStatus(event.target.value as ChangeRequestStatus | ''); setPage(1); }}><option value="">All Statuses</option><option value="PENDING">Pending Review</option><option value="APPROVED">Approved</option><option value="REJECTED">Rejected</option></select></label><label><span>Date Range</span><span className="sl-date-control"><CalendarDays size={16}/><select value={range} onChange={event => { setRange(event.target.value); setPage(1); }}><option>Last 7 Days</option><option>Last 30 Days</option><option>Last 90 Days</option><option>Custom</option></select></span></label>{range === 'Custom' && <div className="sl-v219-custom-date-range"><label><span>From</span><input type="date" value={from} onChange={event => setFrom(event.target.value)}/></label><label><span>To</span><input type="date" value={to} onChange={event => setTo(event.target.value)}/></label></div>}<div className="sl-application-records-filter-actions sl-sa-ingredients-filter-actions"><button className="sl-button" type="button" onClick={reset}>Reset</button></div></div></div>
        <div className="sl-application-records-table-shell sl-sa-ingredients-table-scroll"><table className="sl-application-records-table sl-records-table sl-sa-ingredients-table sl-data-table sl-manager-change-request-table"><colgroup><col/><col/><col/><col/><col/><col/><col/><col/><col/></colgroup><thead><tr>{['#','Request ID','Type','Ingredient / Batch','Requested Change','Submitted By','Date','Status','Actions'].map(value => <th key={value}>{value}</th>)}</tr></thead><tbody>{data?.items.length ? data.items.map((record, index) => <tr key={record.id}><td>{(page - 1) * rows + index + 1}</td><td><span className="sl-canonical-identifier">{record.requestID}</span></td><td>{TYPES[record.requestType]}</td><td>{[record.ingredient ? formatHumanReadableText(record.ingredient.name) : '', record.batch?.batchID].filter(Boolean).join(' · ') || '—'}</td><td>{record.requestedValue ?? record.requestedQuantity ?? record.requestedUnit ?? record.requestDescription ?? 'Structured Request'}</td><td>{formatHumanReadableText(record.requestedBy.name)}</td><td>{formatDateTime(record.createdAt)}</td><td><Status tone={record.status === 'APPROVED' ? 'success' : record.status === 'REJECTED' ? 'critical' : 'attention'}>{statusLabel(record.status)}</Status></td><td className="sl-application-row-actions">{record.status === 'PENDING' ? <button className="sl-button sl-button-compact" type="button" onClick={event => void openReview(record, event.currentTarget)}>Review</button> : <button className="sl-button sl-button-compact" type="button" onClick={event => void openReview(record, event.currentTarget)}>View</button>}</td></tr>) : <tr><td colSpan={9} className="sl-empty-cell"><DataState kind={failed ? 'error' : data === null ? 'loading' : 'empty'} title={failed ? 'Data unavailable' : data === null ? 'Loading requests' : search || type || status ? 'No matching records' : 'No requests yet'} description={failed ? 'The request service could not be reached.' : data === null ? 'Retrieving change requests.' : 'Change requests will appear here after staff submit them.'}/></td></tr>}</tbody></table></div><footer className="sl-application-records-footer sl-records-footer sl-sa-ingredients-footer"><label>Rows per page <select value={rows} onChange={event => { setRows(Number(event.target.value)); setPage(1); }}>{PAGE_SIZES.map(value => <option key={value}>{value}</option>)}</select></label><Pagination compact page={page} pageSize={rows} total={data?.total ?? 0} itemLabel="request records" onPageChange={setPage}/></footer>
      </section>
    </div>
    <Dialog open={selected !== null} showClose={false} title={<span className="sl-account-dialog-heading"><span className="sl-account-dialog-icon"><FileText size={18}/></span><span><span className="sl-account-dialog-title">Review Change Request</span><small>{selected ? TYPES[selected.requestType] : 'View request details.'}</small></span></span>} onDismiss={() => setSelected(null)} returnFocus={reviewTrigger} className="sl-add-user-dialog sl-account-reference-dialog sl-ingredient-view-dialog" actions={selected?.status === 'PENDING' ? <><button className="sl-button sl-button-danger" type="button" onClick={() => setConfirming('reject')}>Reject</button><button className="sl-button sl-button-primary" type="button" onClick={() => setConfirming('approve')}>Approve</button></> : <button className="sl-button" type="button" onClick={() => setSelected(null)}>Close</button>}><dl className="sl-manager-detail-grid">{selected && detailRows(selected).map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl></Dialog>
    <Dialog open={confirming === 'approve'} showClose={false} busy={busy} title="Approve Change Request?" onDismiss={() => setConfirming(null)} actions={<><button className="sl-button" type="button" onClick={() => setConfirming(null)}>Cancel</button><button className="sl-button sl-button-primary" type="button" onClick={() => void decide()} disabled={busy}>Approve Request</button></>}><p className="sl-description">This records the Manager&apos;s approval decision and creates the corresponding audit record. The approved request does not automatically modify inventory or master data.</p>{reviewError && <p className="sl-inline-notice sl-inline-notice-error">{reviewError}</p>}</Dialog>
    <Dialog open={confirming === 'reject'} showClose={false} busy={busy} title="Reject Change Request?" onDismiss={() => setConfirming(null)} actions={<><button className="sl-button" type="button" onClick={() => setConfirming(null)}>Cancel</button><button className="sl-button sl-button-danger" type="button" onClick={() => void decide()} disabled={busy}>Reject Request</button></>}><label className="sl-manager-review-note"><span>Rejection reason</span><textarea rows={4} value={reviewNote} onChange={event => { setReviewNote(event.target.value); setReviewError(''); }}/></label>{reviewError && <p className="sl-inline-notice sl-inline-notice-error">{reviewError}</p>}</Dialog>
  </>;
}
