import { useEffect, useRef, useState } from 'react';
import { AlertTriangle, CheckCircle2, CircleX, Clock3, FileInput, FileText, Search } from 'lucide-react';
import { CHANGE_REQUEST_TYPES, CHANGE_REQUEST_TYPE_LABELS, approveChangeRequest, changeRequestComparison, changeRequestTypeLabel, getChangeRequest, getManagerChangeRequestSummary, listChangeRequests, rejectChangeRequest, type ChangeRequest, type ChangeRequestStatus, type ChangeRequestType } from '../../services/change-requests';
import { formatDateTime } from '../../utils/date-time';
import { formatHumanReadableText } from '../../utils/display-text';
import { ChangeRequestDetailsDialog } from './ChangeRequestDetailsDialog';
import { InventoryStaffModal, InventoryStaffModalForm } from './InventoryStaffModal';
import { DataState, PageHeader, Pagination, Status } from './primitives';
const PAGE_SIZES=[10,15,50,100,150] as const;
const dateInput=(date:Date)=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;
export function ConnectedManagerChangeRequestsPage(){
 const reviewTrigger=useRef<HTMLElement>(null); const [search,setSearch]=useState(''),[type,setType]=useState<ChangeRequestType|''>(''),[status,setStatus]=useState<ChangeRequestStatus|''>(''),[range,setRange]=useState('Last 30 Days'),[from,setFrom]=useState(''),[to,setTo]=useState(''),[page,setPage]=useState(1),[rows,setRows]=useState(10);
 const [data,setData]=useState<{items:ChangeRequest[];total:number}|null>(null),[counts,setCounts]=useState<any>(null),[failed,setFailed]=useState(false),[selected,setSelected]=useState<ChangeRequest|null>(null),[confirming,setConfirming]=useState<'approve'|'reject'|null>(null),[reviewNote,setReviewNote]=useState(''),[reviewError,setReviewError]=useState(''),[reviewTouched,setReviewTouched]=useState(false),[busy,setBusy]=useState(false);
 const dates=()=>{if(range==='Custom')return{from:from||undefined,to:to||undefined};const days=range==='Last 7 Days'?7:range==='Last 90 Days'?90:30,start=new Date();start.setDate(start.getDate()-days+1);return{from:dateInput(start),to:dateInput(new Date())}};
 const load=(signal?:AbortSignal)=>Promise.all([listChangeRequests({page,pageSize:rows,search:search.trim()||undefined,type:type||undefined,status:status||undefined,currentOnly:true,...dates()},signal),getManagerChangeRequestSummary(dates(),signal),listChangeRequests({page:1,pageSize:10,currentOnly:true},signal)]).then(([records,summary,scope])=>{setData(records);setCounts({total:summary.totalRequests,pending:summary.pending,approved:summary.approved,rejected:summary.rejected,scopeTotal:scope.total});setFailed(false)}).catch(e=>{if((e as Error).name!=='AbortError')setFailed(true)});
 useEffect(()=>{const controller=new AbortController(),timer=window.setTimeout(()=>void load(controller.signal),200);return()=>{window.clearTimeout(timer);controller.abort()}},[search,type,status,range,from,to,page,rows]);
 const openReview=async(record:ChangeRequest,trigger:HTMLElement)=>{reviewTrigger.current=trigger;try{setSelected(await getChangeRequest(record.id))}catch{setSelected(record)}};
 const closeDecision=()=>{setConfirming(null);setReviewNote('');setReviewError('');setReviewTouched(false)};
 const decide=async()=>{if(!selected||!confirming)return;if(confirming==='reject'&&!reviewNote.trim()){setReviewTouched(true);setReviewError('Enter the reason for rejecting this request.');return}setBusy(true);try{if(confirming==='approve')await approveChangeRequest(selected.id);else await rejectChangeRequest(selected.id,reviewNote.trim());closeDecision();setSelected(null);await load()}catch{setReviewError('Unable to record this decision.')}finally{setBusy(false)}};
 const reset=()=>{setSearch('');setType('');setStatus('');setRange('Last 30 Days');setFrom('');setTo('');setPage(1)};
 return <><PageHeader eyebrow="Operations" title="Change Requests" description="Review and decide on controlled ingredient master-data changes submitted by your team."/><div className="sl-admin-view sl-manager-change-requests-live"><section className="sl-sa-kpis sl-dashboard-source-kpis">{[[FileInput,'Total Requests',counts?.total,'Requests in the selected period'],[Clock3,'Pending Review',counts?.pending,'Requires your action'],[CheckCircle2,'Approved',counts?.approved,'Approved in the selected period'],[CircleX,'Rejected',counts?.rejected,'Rejected in the selected period']].map(([Icon,label,value,helper],index)=><article className="sl-sa-kpi" data-tone={['brand','info','attention','critical'][index]} key={String(label)}><span className="sl-sa-kpi-icon"><Icon/></span><div><span>{label}</span><strong>{failed?'—':value??'—'}</strong><small>{failed?'Request data unavailable':helper}</small></div></article>)}</section>
 <section className="sl-manager-request-records sl-application-records sl-sa-ingredients-table-card sl-sa-account-pattern-records"><header className="sl-application-records-header sl-staff-usage-card-head"><span className="sl-staff-usage-head-icon"><FileText/></span><h2>Change Request Records</h2></header><div className="sl-application-records-filters sl-sa-ingredients-table-filters"><div className="sl-application-records-toolbar sl-sa-ingredients-filter-card" data-filter-layout="records-five"><label className="sl-application-records-search sl-sa-ingredients-search"><span>Search</span><span><Search size={17}/><input value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}} placeholder="Search by request ID or ingredient..."/></span></label><label><span>Request Type</span><select value={type} onChange={e=>{setType(e.target.value as ChangeRequestType|'');setPage(1)}}><option value="">All Types</option>{CHANGE_REQUEST_TYPES.map(v=><option value={v} key={v}>{CHANGE_REQUEST_TYPE_LABELS[v]}</option>)}</select></label><label><span>Status</span><select value={status} onChange={e=>{setStatus(e.target.value as ChangeRequestStatus|'');setPage(1)}}><option value="">All Statuses</option><option value="PENDING">Pending Review</option><option value="APPROVED">Approved</option><option value="REJECTED">Rejected</option></select></label><label><span>Date Range</span><select value={range} onChange={e=>{setRange(e.target.value);setPage(1)}}><option>Last 7 Days</option><option>Last 30 Days</option><option>Last 90 Days</option><option>Custom</option></select></label>{range==='Custom'&&<div className="sl-v219-custom-date-range"><label><span>From</span><input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label><span>To</span><input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label></div>}<div className="sl-sa-ingredients-filter-actions"><button className="sl-button" type="button" onClick={reset}>Reset</button></div></div></div>
 <div className="sl-application-records-table-shell sl-sa-ingredients-table-scroll"><table className="sl-application-records-table sl-records-table sl-sa-ingredients-table"><thead><tr>{['Request ID','Type','Ingredient','Requested Change','Submitted By','Submitted','Status','Actions'].map(v=><th key={v}>{v}</th>)}</tr></thead><tbody>{data?.items.length?data.items.map(record=><tr key={record.id}><td><span className="sl-canonical-identifier">{record.requestID}</span></td><td>{changeRequestTypeLabel(record.requestType)}</td><td className="sl-emphasized-value">{record.ingredient?formatHumanReadableText(record.ingredient.name):'—'}</td><td>{changeRequestComparison(record)}</td><td>{formatHumanReadableText(record.requestedBy.name)}</td><td>{formatDateTime(record.createdAt)}</td><td><Status tone={record.status==='APPROVED'?'success':record.status==='REJECTED'?'critical':'attention'}>{record.status==='PENDING'?'Pending Review':record.status}</Status></td><td><button className="sl-button sl-button-compact" type="button" onClick={e=>void openReview(record,e.currentTarget)}>{record.status==='PENDING'?'Review':'View'}</button></td></tr>):<tr><td colSpan={8} className="sl-empty-cell"><DataState kind={failed?'error':data===null?'loading':'empty'} title={failed?'Data unavailable':data===null?'Loading requests':counts?.scopeTotal>0?'No matching records':'No requests yet'} description={failed?'The request service could not be reached.':data===null?'Retrieving protected ingredient change requests.':counts?.scopeTotal>0?'No change requests match the current filters.':'No change requests have been submitted.'}/></td></tr>}</tbody></table></div><footer className="sl-application-records-footer sl-sa-ingredients-footer"><label>Rows per page <select value={rows} onChange={e=>{setRows(Number(e.target.value));setPage(1)}}>{PAGE_SIZES.map(v=><option key={v}>{v}</option>)}</select></label><Pagination compact mutedWhenEmpty page={page} pageSize={rows} total={data?.total??0} itemLabel="request records" onPageChange={setPage}/></footer></section></div>
 <ChangeRequestDetailsDialog manager request={selected} title="Review Change Request" onDismiss={()=>setSelected(null)} returnFocus={reviewTrigger} actions={selected?.status==='PENDING'?<><button className="sl-button sl-button-danger" onClick={()=>{setReviewNote('');setReviewError('');setReviewTouched(false);setConfirming('reject')}}>Reject</button><button className="sl-button sl-button-primary" onClick={()=>{setReviewError('');setConfirming('approve')}}>Approve Request</button></>:undefined}/>
 <InventoryStaffModal open={confirming==='approve'} showClose={false} busy={busy} title="Approve and apply change?" subtitle="Apply the validated Ingredient master-data change and record the decision." Icon={CheckCircle2} onDismiss={closeDecision} returnFocus={reviewTrigger} actions={<><button className="sl-button" onClick={closeDecision}>Cancel</button><button className="sl-button sl-button-primary" onClick={()=>void decide()} disabled={busy}>Approve Request</button></>}><div className="sl-application-modal-content"><p className="sl-description">The approved value will become the authoritative Ingredient master-data value.</p>{reviewError&&<p className="sl-inline-notice sl-inline-notice-error">{reviewError}</p>}</div></InventoryStaffModal>
 <InventoryStaffModal open={confirming==='reject'} showClose={false} busy={busy} title="Reject Change Request?" subtitle="Record why this controlled change cannot be approved." Icon={AlertTriangle} onDismiss={closeDecision} returnFocus={reviewTrigger}>
  <InventoryStaffModalForm formId="manager-reject-change-request" onSubmit={event=>{event.preventDefault();void decide()}} secondaryLabel="Cancel" onSecondary={closeDecision} primaryLabel="Reject Request" busy={busy}>
   <label className="sl-staff-modal-wide"><span>Rejection reason</span><textarea rows={4} placeholder="Enter the reason for rejecting this request..." value={reviewNote} aria-invalid={Boolean(reviewError)} aria-describedby={reviewError?'manager-rejection-error':undefined} onBlur={()=>{setReviewTouched(true);if(!reviewNote.trim())setReviewError('Enter the reason for rejecting this request.')}} onChange={event=>{setReviewNote(event.target.value);if(event.target.value.trim())setReviewError('');else if(reviewTouched)setReviewError('Enter the reason for rejecting this request.')}}/></label>{reviewError&&<p id="manager-rejection-error" className="sl-field-error sl-staff-modal-wide" role="alert">{reviewError}</p>}
  </InventoryStaffModalForm>
 </InventoryStaffModal></>;
}
