import { useEffect, useRef, useState } from 'react';
import { CheckCircle2, CircleX, Clock3, Eye, FileInput, FileText, Search } from 'lucide-react';
import { CHANGE_REQUEST_TYPES, CHANGE_REQUEST_TYPE_LABELS, approveChangeRequest, changeRequestStatusLabel, changeRequestTypeLabel, getChangeRequest, getManagerChangeRequestSummary, listChangeRequests, rejectChangeRequest, type ChangeRequest, type ChangeRequestStatus, type ChangeRequestType } from '../../services/change-requests';
import { formatDateTime } from '../../utils/date-time';
import { formatHumanReadableText } from '../../utils/display-text';
import { ChangeRequestDetailsDialog } from './ChangeRequestDetailsDialog';
import { renderManagerApprovalForm } from './ManagerApprovalForm';
import { renderManagerRejectionForm } from './ManagerRejectionForm';
import { FilterSelect } from './FilterSelect';
import { DataState, PageHeader, Pagination, Status } from './primitives';
const PAGE_SIZES=[10,15,50,100,150] as const;
const dateInput=(date:Date)=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;
export function ConnectedManagerChangeRequestsPage(){
 const reviewTrigger=useRef<HTMLElement>(null), rejectTrigger=useRef<HTMLButtonElement>(null), approveTrigger=useRef<HTMLButtonElement>(null), rejectionField=useRef<HTMLTextAreaElement>(null); const [search,setSearch]=useState(''),[type,setType]=useState<ChangeRequestType|''>(''),[status,setStatus]=useState<ChangeRequestStatus|''>(''),[range,setRange]=useState('Last 30 Days'),[from,setFrom]=useState(''),[to,setTo]=useState(''),[page,setPage]=useState(1),[rows,setRows]=useState(10);
 const [data,setData]=useState<{items:ChangeRequest[];total:number}|null>(null),[counts,setCounts]=useState<any>(null),[failed,setFailed]=useState(false),[selected,setSelected]=useState<ChangeRequest|null>(null),[confirming,setConfirming]=useState<'approve'|'reject'|null>(null),[reviewNote,setReviewNote]=useState(''),[reviewError,setReviewError]=useState(''),[busy,setBusy]=useState(false);
 const dates=()=>{if(range==='Custom')return{from:from||undefined,to:to||undefined};const days=range==='Last 7 Days'?7:range==='Last 90 Days'?90:30,start=new Date();start.setDate(start.getDate()-days+1);return{from:dateInput(start),to:dateInput(new Date())}};
 const load=(signal?:AbortSignal)=>Promise.all([listChangeRequests({page,pageSize:rows,search:search.trim()||undefined,type:type||undefined,status:status||undefined,currentOnly:true,...dates()},signal),getManagerChangeRequestSummary(dates(),signal),listChangeRequests({page:1,pageSize:10,currentOnly:true},signal)]).then(([records,summary,scope])=>{setData(records);setCounts({total:summary.totalRequests,pending:summary.pending,approved:summary.approved,rejected:summary.rejected,scopeTotal:scope.total});setFailed(false)}).catch(e=>{if((e as Error).name!=='AbortError')setFailed(true)});
 useEffect(()=>{const controller=new AbortController(),timer=window.setTimeout(()=>void load(controller.signal),200);return()=>{window.clearTimeout(timer);controller.abort()}},[search,type,status,range,from,to,page,rows]);
 const openReview=async(record:ChangeRequest,trigger:HTMLElement)=>{reviewTrigger.current=trigger;try{setSelected(await getChangeRequest(record.id))}catch{setSelected(record)}};
 // Back to Review abandons the selected decision only: it submits nothing, drops
 // the draft reason and returns focus to the control that opened that decision.
 const closeDecision=()=>{const reviewed=confirming;setConfirming(null);setReviewNote('');setReviewError('');(reviewed==='approve'?approveTrigger:rejectTrigger).current?.focus()};
 // Reject mode reveals the inline reason field inside the scrolling body of the
 // review dialog: focus it, then bring it into view so the required field and
 // the Reject Request action are both reachable without hunting on short screens.
 useEffect(()=>{if(confirming!=='reject')return;const field=rejectionField.current;if(!field)return;field.focus({preventScroll:true});field.scrollIntoView({block:'nearest'})},[confirming]);
 const dismissReview=()=>{if(busy)return;setSelected(null);setConfirming(null);setReviewNote('');setReviewError('')};
 // One guarded path owns both decisions: it refuses a second submit while a request
 // is in flight, and success is never reflected before the server confirms it,
 // because the dialog closes only after the call resolves.
 const decide=async()=>{if(!selected||!confirming||busy)return;if(confirming==='reject'&&!reviewNote.trim()){setReviewError('Enter the reason for rejecting this request.');rejectionField.current?.focus();return}setBusy(true);try{if(confirming==='approve')await approveChangeRequest(selected.id);else await rejectChangeRequest(selected.id,reviewNote.trim());setConfirming(null);setReviewNote('');setReviewError('');setSelected(null);await load()}catch{setReviewError(confirming==='approve'?'Unable to approve this request.':'Unable to record this decision.')}finally{setBusy(false)}};
 const reset=()=>{setSearch('');setType('');setStatus('');setRange('Last 30 Days');setFrom('');setTo('');setPage(1)};
 return <><PageHeader eyebrow="Operations" title="Change Requests" description="Review and decide on controlled ingredient master-data changes submitted by your team."/><div className="sl-admin-view sl-manager-change-requests-live"><section className="sl-sa-kpis sl-dashboard-source-kpis">{[[FileInput,'Total Requests',counts?.total,'Requests in the selected period'],[Clock3,'Pending',counts?.pending,'Requires your action'],[CheckCircle2,'Approved',counts?.approved,'Approved in the selected period'],[CircleX,'Rejected',counts?.rejected,'Rejected in the selected period']].map(([Icon,label,value,helper],index)=><article className="sl-sa-kpi" data-tone={['brand','info','attention','critical'][index]} key={String(label)}><span className="sl-sa-kpi-icon"><Icon/></span><div><span>{label}</span><strong>{failed?'—':value??'—'}</strong><small>{failed?'Request data unavailable':helper}</small></div></article>)}</section>
 <section className="sl-manager-request-records sl-application-records sl-sa-ingredients-table-card sl-sa-account-pattern-records"><header className="sl-application-records-header sl-staff-usage-card-head"><span className="sl-staff-usage-head-icon"><FileText/></span><h2>Change Request Records</h2></header><div className="sl-application-records-filters sl-sa-ingredients-table-filters"><div className="sl-application-records-toolbar sl-sa-ingredients-filter-card" data-filter-layout="records-five"><label className="sl-application-records-search sl-sa-ingredients-search"><span>Search</span><span><Search size={17}/><input value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}} placeholder="Search by request ID or ingredient..."/></span></label><label><span>Request Type</span><FilterSelect ariaLabel="Filter requests by type" value={type} options={[{value:'',label:'All Types'},...CHANGE_REQUEST_TYPES.map(value=>({value,label:CHANGE_REQUEST_TYPE_LABELS[value]}))]} onChange={value=>{setType(value as ChangeRequestType|'');setPage(1)}}/></label><label><span>Status</span><FilterSelect ariaLabel="Filter requests by status" value={status} options={[{value:'',label:'All Statuses'},{value:'PENDING',label:'Pending'},{value:'APPROVED',label:'Approved'},{value:'REJECTED',label:'Rejected'}]} onChange={value=>{setStatus(value as ChangeRequestStatus|'');setPage(1)}}/></label><label><span>Date Range</span><FilterSelect ariaLabel="Filter requests by date range" value={range} options={['Last 7 Days','Last 30 Days','Last 90 Days','Custom'].map(value=>({value,label:value}))} onChange={value=>{setRange(value);setPage(1)}}/></label>{range==='Custom'&&<div className="sl-v219-custom-date-range"><label><span>From</span><input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label><span>To</span><input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label></div>}<div className="sl-sa-ingredients-filter-actions"><button className="sl-button" type="button" onClick={reset}>Reset</button></div></div></div>
 <div className="sl-application-records-table-shell sl-sa-ingredients-table-scroll"><table className="sl-application-records-table sl-records-table sl-sa-ingredients-table"><thead><tr>{['Request ID','Type','Ingredient','Submitted By','Submitted','Status','Actions'].map(v=><th key={v}>{v}</th>)}</tr></thead><tbody>{data?.items.length?data.items.map(record=><tr key={record.id}><td><span className="sl-canonical-identifier sl-canonical-identifier-emphasis">{record.requestID}</span></td><td>{changeRequestTypeLabel(record.requestType)}</td><td className="sl-manager-request-ingredient" title={record.ingredient?formatHumanReadableText(record.ingredient.name):undefined}><span className="sl-manager-request-ingredient-preview" aria-label={record.ingredient?formatHumanReadableText(record.ingredient.name):undefined}>{record.ingredient?formatHumanReadableText(record.ingredient.name):'—'}</span></td><td>{formatHumanReadableText(record.requestedBy.name)}</td><td>{formatDateTime(record.createdAt)}</td><td><Status tone={record.status==='APPROVED'?'success':record.status==='REJECTED'?'critical':'attention'}>{changeRequestStatusLabel(record.status)}</Status></td><td className="sl-sa-ingredients-actions-cell"><div className="sl-staff-waste-row-actions" aria-label={`${record.requestID} actions`}><button className="sl-button sl-icon-button" type="button" aria-label={record.status==='PENDING'?`Review Request ${record.requestID}`:`View Request ${record.requestID}`} title={record.status==='PENDING'?'Review Request':'View Request'} onClick={e=>void openReview(record,e.currentTarget)}><Eye size={16} aria-hidden="true"/></button></div></td></tr>):<tr><td colSpan={7} className="sl-empty-cell"><DataState kind={failed?'error':data===null?'loading':'empty'} title={failed?'Data unavailable':data===null?'Loading requests':counts?.scopeTotal>0?'No matching records':'No requests yet'} description={failed?'The request service could not be reached.':data===null?'Retrieving protected ingredient change requests.':counts?.scopeTotal>0?'No change requests match the current filters.':'No change requests have been submitted.'}/></td></tr>}</tbody></table></div><footer className="sl-application-records-footer sl-sa-ingredients-footer"><label>Rows per page <select value={rows} onChange={e=>{setRows(Number(e.target.value));setPage(1)}}>{PAGE_SIZES.map(v=><option key={v}>{v}</option>)}</select></label><Pagination compact mutedWhenEmpty page={page} pageSize={rows} total={data?.total??0} itemLabel="request records" onPageChange={setPage}/></footer></section></div>
 <ChangeRequestDetailsDialog manager request={selected} title="Review Change Request" onDismiss={dismissReview} returnFocus={reviewTrigger} busy={busy} reviewForm={confirming==='reject'&&selected?.status==='PENDING'?renderManagerRejectionForm({note:reviewNote,setNote:setReviewNote,error:reviewError,setError:setReviewError,field:rejectionField,onSubmit:()=>void decide()}):confirming==='approve'&&selected?.status==='PENDING'?renderManagerApprovalForm({record:selected,error:reviewError,onSubmit:()=>void decide()}):undefined} actions={selected?.status==='PENDING'?(confirming==='reject'?<><button type="button" className="sl-button" disabled={busy} onClick={closeDecision}>Back to Review</button><button type="submit" form="manager-reject-change-request" className="sl-button sl-button-danger sl-manager-request-reject" disabled={busy}>Reject Request</button></>:confirming==='approve'?<><button type="button" className="sl-button" disabled={busy} onClick={closeDecision}>Back to Review</button><button type="submit" form="manager-approve-change-request" className="sl-button sl-button-primary" disabled={busy}>Confirm Approval</button></>:<><button ref={rejectTrigger} type="button" className="sl-button sl-button-danger sl-manager-request-reject" onClick={()=>{setReviewNote('');setReviewError('');setConfirming('reject')}}>Reject</button><button ref={approveTrigger} type="button" className="sl-button sl-button-primary" onClick={()=>{setReviewError('');setConfirming('approve')}}>Approve Request</button></>):undefined}/>
 {/* Approval is confirmed inline, in this same dialog: the comparison and the reason
 stay on screen while the footer swaps to Back to Review and Confirm Approval, so a
 decision stays deliberate without stacking a second dialog over the first. */}
 </>;
}
