import { useEffect, useRef, useState, type FormEvent } from 'react';
import { FileInput, Plus, Search } from 'lucide-react';
import { CHANGE_REQUEST_TARGET_LABELS, CHANGE_REQUEST_TYPES, CHANGE_REQUEST_TYPE_LABELS, CHANGE_REQUEST_UNITS, changeRequestTypeLabel, changeRequestValue, createChangeRequest, getChangeRequestSummary, listChangeRequests, type ChangeRequest, type ChangeRequestStatus, type ChangeRequestType } from '../../services/change-requests';
import { listIngredients, type Ingredient } from '../../services/ingredients';
import { formatDateTime } from '../../utils/date-time';
import { Dialog } from '../../components/application/Dialog';
import { ChangeRequestDetailsDialog } from '../../components/application/ChangeRequestDetailsDialog';
import { DataState, PageHeader, Pagination, Status } from '../../components/application/primitives';
import { ConnectedManagerChangeRequestsPage } from '../../components/application/ManagerChangeRequestsPage';
import { useApplicationWorkspace } from '../../components/application/ApplicationWorkspace';

const PAGE_SIZES=[10,15,50,100,150] as const, CATEGORIES=['Dairy','Produce','Bakery','Pantry','Meat','Seafood','Frozen','Beverages','Other'];
const fieldByType:Record<ChangeRequestType,keyof Ingredient>={MINIMUM_STOCK_CHANGE:'minimumStock',STANDARD_UNIT_COST_CHANGE:'standardUnitCost',CATEGORY_CHANGE:'category',BRAND_CHANGE:'brand',DESCRIPTION_CHANGE:'description',UNIT_OF_MEASURE_CHANGE:'unitOfMeasure',DEFAULT_SHELF_LIFE_CHANGE:'defaultShelfLifeDays'};
function InventoryStaffChangeRequests(){
 const addButton=useRef<HTMLButtonElement>(null); const detailTrigger=useRef<HTMLElement>(null);
 const [items,setItems]=useState<ChangeRequest[]|null>(null),[total,setTotal]=useState(0),[summary,setSummary]=useState<any>(null),[ingredients,setIngredients]=useState<Ingredient[]>([]),[failed,setFailed]=useState(false);
 const [search,setSearch]=useState(''),[type,setType]=useState(''),[status,setStatus]=useState(''),[page,setPage]=useState(1),[rows,setRows]=useState(10),[open,setOpen]=useState(false),[detail,setDetail]=useState<ChangeRequest|null>(null);
 const [draft,setDraft]=useState<{requestType:ChangeRequestType|'';ingredientId:string;requestedValue:string;reason:string}>({requestType:'',ingredientId:'',requestedValue:'',reason:''}),[errors,setErrors]=useState<Record<string,string>>({}),[touched,setTouched]=useState<Record<string,boolean>>({}),[submitted,setSubmitted]=useState(false),[busy,setBusy]=useState(false);
 const load=(signal?:AbortSignal)=>Promise.all([listChangeRequests({page,pageSize:rows,search:search.trim()||undefined,type:(type||undefined) as ChangeRequestType|undefined,status:(status||undefined) as ChangeRequestStatus|undefined},signal),getChangeRequestSummary(signal)]).then(([records,nextSummary])=>{setItems(records.items);setTotal(records.total);setSummary(nextSummary);setFailed(false)}).catch(e=>{if((e as Error).name!=='AbortError')setFailed(true)});
 useEffect(()=>{const controller=new AbortController(),timer=window.setTimeout(()=>void load(controller.signal),200);return()=>{window.clearTimeout(timer);controller.abort()}},[search,type,status,page,rows]);
 useEffect(()=>{const controller=new AbortController();listIngredients(1,150,'','',controller.signal).then(result=>setIngredients(result.items)).catch(()=>setIngredients([]));return()=>controller.abort()},[]);
 const selected=ingredients.find(item=>item.id===draft.ingredientId), field=draft.requestType?fieldByType[draft.requestType]:undefined, current=selected&&field?String(selected[field]??'—'):'—';
 const validate=()=>{const next:Record<string,string>={};if(!draft.requestType)next.requestType='Select a request type.';if(!draft.ingredientId)next.ingredientId='Select an ingredient.';if(!draft.requestedValue.trim())next.requestedValue='Enter the requested value.';else if(draft.requestType&&['MINIMUM_STOCK_CHANGE','STANDARD_UNIT_COST_CHANGE','DEFAULT_SHELF_LIFE_CHANGE'].includes(draft.requestType)&&(!Number.isFinite(Number(draft.requestedValue))||Number(draft.requestedValue)<0))next.requestedValue='Enter a valid value.';if(!draft.reason.trim())next.reason='Enter a reason.';return next};
 const submit=async(e:FormEvent)=>{e.preventDefault();setSubmitted(true);const next=validate();setErrors(next);if(Object.keys(next).length)return;setBusy(true);try{const numeric=['MINIMUM_STOCK_CHANGE','STANDARD_UNIT_COST_CHANGE','DEFAULT_SHELF_LIFE_CHANGE'].includes(draft.requestType);await createChangeRequest({requestType:draft.requestType as ChangeRequestType,ingredientId:draft.ingredientId,requestedValue:numeric?Number(draft.requestedValue):draft.requestedValue.trim(),reason:draft.reason.trim()});setOpen(false);setDraft({requestType:'',ingredientId:'',requestedValue:'',reason:''});setTouched({});setSubmitted(false);await load()}finally{setBusy(false)}};
 const show=(name:string)=>Boolean(errors[name]&&(submitted||touched[name])); const input=(name:keyof typeof draft,value:string)=>{setDraft(v=>({...v,[name]:value}));setErrors(validate())};
 return <><PageHeader eyebrow="Operations" title="My Requests" description="Submit and track controlled Ingredient master-data change requests."/>
 <div className="sl-admin-view"><section className="sl-sa-kpis sl-kpi-reference-v201">{[['Total Requests',summary?.totalRequests],['Pending Review',summary?.pending],['Approved',summary?.approved],['Rejected requests',summary?.rejected]].map(([label,value],index)=><article className="sl-sa-kpi" data-tone={['brand','info','attention','critical'][index]} key={label}><span className="sl-sa-kpi-icon"><FileInput/></span><div><span>{label}</span><strong>{failed?'—':value??'—'}</strong><small>{failed?'Request data unavailable':'Your submitted requests'}</small></div></article>)}</section>
 <section className="sl-application-records sl-sa-ingredients-table-card sl-sa-account-pattern-records"><header className="sl-application-records-header sl-staff-usage-card-head"><span className="sl-staff-usage-head-icon"><FileInput/></span><h2>Change Request Records</h2></header><div className="sl-sa-ingredients-table-filters"><div className="sl-sa-ingredients-filter-card sl-staff-requests-toolbar"><label className="sl-sa-ingredients-search"><span>Search records</span><div><Search size={17}/><input value={search} placeholder="Search by request ID or ingredient..." onChange={e=>{setSearch(e.target.value);setPage(1)}}/></div></label><label><span>Type</span><select value={type} onChange={e=>{setType(e.target.value);setPage(1)}}><option value="">All Types</option>{CHANGE_REQUEST_TYPES.map(value=><option value={value} key={value}>{CHANGE_REQUEST_TYPE_LABELS[value]}</option>)}</select></label><label><span>Status</span><select value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}}><option value="">All Statuses</option><option value="PENDING">Pending Review</option><option value="APPROVED">Approved</option><option value="REJECTED">Rejected</option></select></label><div className="sl-sa-ingredients-filter-actions"><button type="button" className="sl-button" onClick={()=>{setSearch('');setType('');setStatus('');setPage(1)}}>Reset</button><button ref={addButton} className="sl-button sl-button-primary" type="button" onClick={()=>{setDraft({requestType:'',ingredientId:'',requestedValue:'',reason:''});setErrors({});setTouched({});setSubmitted(false);setOpen(true)}}><Plus size={16}/>New Request</button></div></div></div>
 <div className="sl-application-records-table-shell sl-sa-ingredients-table-scroll"><table className="sl-application-records-table sl-records-table sl-sa-ingredients-table"><thead><tr>{['Request ID','Type','Ingredient','Requested Change','Submitted On','Status'].map(v=><th key={v}>{v}</th>)}</tr></thead><tbody>{items?.length?items.map(record=><tr key={record.id} className="sl-detail-enabled-row" tabIndex={0} onClick={e=>{detailTrigger.current=e.currentTarget;setDetail(record)}} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();detailTrigger.current=e.currentTarget;setDetail(record)}}}><td><span className="sl-canonical-identifier">{record.requestID}</span></td><td>{changeRequestTypeLabel(record.requestType)}</td><td className="sl-emphasized-value">{record.ingredient?.name??'—'}</td><td>{changeRequestValue(record,record.requestedValue)}</td><td>{formatDateTime(record.createdAt)}</td><td><Status tone={record.status==='APPROVED'?'success':record.status==='REJECTED'?'critical':'attention'}>{record.status==='PENDING'?'Pending Review':record.status}</Status></td></tr>):<tr><td colSpan={6} className="sl-empty-cell"><DataState kind={failed?'error':items===null?'loading':'empty'} title={failed?'Data unavailable':items===null?'Loading requests':search||type||status?'No matching records':'No requests yet'} description={failed?'The request service could not be reached.':'Submitted requests will appear here.'}/></td></tr>}</tbody></table></div><footer className="sl-application-records-footer sl-sa-ingredients-footer"><label>Rows per page <select value={rows} onChange={e=>{setRows(Number(e.target.value));setPage(1)}}>{PAGE_SIZES.map(v=><option key={v}>{v}</option>)}</select></label><Pagination compact page={page} pageSize={rows} total={total} itemLabel="request records" onPageChange={setPage}/></footer></section></div>
 <Dialog open={open} showClose={false} busy={busy} title="New Change Request" onDismiss={()=>setOpen(false)} returnFocus={addButton} actions={<><button type="button" className="sl-button" onClick={()=>setOpen(false)}>Cancel</button><button type="submit" form="new-change-request" className="sl-button sl-button-primary" disabled={busy}>Submit Request</button></>}><form id="new-change-request" className="sl-staff-my-request-form" onSubmit={submit}><label><span>Request Type</span><select value={draft.requestType} onBlur={()=>setTouched(v=>({...v,requestType:true}))} onChange={e=>{setDraft(v=>({...v,requestType:e.target.value as ChangeRequestType,requestedValue:''}));setErrors({})}}><option value="">Select request type</option>{CHANGE_REQUEST_TYPES.map(v=><option key={v} value={v}>{CHANGE_REQUEST_TYPE_LABELS[v]}</option>)}</select>{show('requestType')&&<span className="sl-field-error">{errors.requestType}</span>}</label><label><span>Ingredient</span><select value={draft.ingredientId} onBlur={()=>setTouched(v=>({...v,ingredientId:true}))} onChange={e=>input('ingredientId',e.target.value)}><option value="">Select ingredient</option>{ingredients.map(v=><option value={v.id} key={v.id}>{v.name}</option>)}</select>{show('ingredientId')&&<span className="sl-field-error">{errors.ingredientId}</span>}</label><label><span>Current Value</span><output className="sl-staff-derived-unit">{current}</output></label><label><span>{field?CHANGE_REQUEST_TARGET_LABELS[field as keyof typeof CHANGE_REQUEST_TARGET_LABELS]:'Requested Value'}</span>{draft.requestType==='CATEGORY_CHANGE'?<select value={draft.requestedValue} onChange={e=>input('requestedValue',e.target.value)}><option value="">Select category</option>{CATEGORIES.map(v=><option key={v}>{v}</option>)}</select>:draft.requestType==='UNIT_OF_MEASURE_CHANGE'?<select value={draft.requestedValue} onChange={e=>input('requestedValue',e.target.value)}><option value="">Select unit</option>{CHANGE_REQUEST_UNITS.map(v=><option key={v}>{v}</option>)}</select>:<input value={draft.requestedValue} inputMode={draft.requestType&&['MINIMUM_STOCK_CHANGE','STANDARD_UNIT_COST_CHANGE','DEFAULT_SHELF_LIFE_CHANGE'].includes(draft.requestType)?'decimal':undefined} onBlur={()=>setTouched(v=>({...v,requestedValue:true}))} onChange={e=>input('requestedValue',e.target.value)}/>} {show('requestedValue')&&<span className="sl-field-error">{errors.requestedValue}</span>}</label><label className="sl-staff-my-request-full"><span>Reason</span><textarea value={draft.reason} onBlur={()=>setTouched(v=>({...v,reason:true}))} onChange={e=>input('reason',e.target.value)}/>{show('reason')&&<span className="sl-field-error">{errors.reason}</span>}</label></form></Dialog>
 <ChangeRequestDetailsDialog request={detail} onDismiss={()=>setDetail(null)} returnFocus={detailTrigger}/></>;
}

export default function ChangeRequests() {
 const { user } = useApplicationWorkspace();
 return user.role === 'Manager' ? <ConnectedManagerChangeRequestsPage /> : <InventoryStaffChangeRequests />;
}
