import { useEffect, useRef, useState, type FormEvent } from 'react';
import { CheckCircle2, Clock3, FileInput, Plus, Search, XCircle } from 'lucide-react';
import { CHANGE_REQUEST_TARGET_LABELS, CHANGE_REQUEST_TYPES, CHANGE_REQUEST_TYPE_LABELS, CHANGE_REQUEST_UNITS, createChangeRequest, getChangeRequestSummary, listChangeRequestIngredients, listChangeRequests, type ChangeRequest, type ChangeRequestIngredientOption, type ChangeRequestStatus, type ChangeRequestType } from '../../services/change-requests';
import { formatStaffChangeRequestValue } from '../../utils/change-request-format';
import { formatDateTime } from '../../utils/date-time';
import { ChangeRequestDetailsDialog, formatChangeRequestSummary } from '../../components/application/ChangeRequestDetailsDialog';
import { InventoryStaffModal, InventoryStaffModalForm } from '../../components/application/InventoryStaffModal';
import { DataState, PageHeader, Pagination, Status } from '../../components/application/primitives';
import { ConnectedManagerChangeRequestsPage } from '../../components/application/ManagerChangeRequestsPage';
import { useApplicationWorkspace } from '../../components/application/ApplicationWorkspace';

const PAGE_SIZES=[10,15,50,100,150] as const, CATEGORIES=['Dairy','Produce','Bakery','Pantry','Meat','Seafood','Frozen','Beverages','Other'];
const DATE_RANGES=['All dates','Today','Last 7 Days','Last 30 Days','Custom range'] as const;
const localDate=(date:Date)=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;
const datesFor=(range:(typeof DATE_RANGES)[number],from:string,to:string)=>{const now=new Date();if(range==='Today'){const today=localDate(now);return{from:today,to:today}}if(range==='Last 7 Days'||range==='Last 30 Days'){const start=new Date(now);start.setDate(now.getDate()-(range==='Last 7 Days'?6:29));return{from:localDate(start),to:localDate(now)}}return range==='Custom range'?{from,to}:{}};
const fieldByType:Record<ChangeRequestType,keyof ChangeRequestIngredientOption>={MINIMUM_STOCK_CHANGE:'minimumStock',STANDARD_UNIT_COST_CHANGE:'standardUnitCost',CATEGORY_CHANGE:'category',BRAND_CHANGE:'brand',DESCRIPTION_CHANGE:'description',UNIT_OF_MEASURE_CHANGE:'unitOfMeasure',DEFAULT_SHELF_LIFE_CHANGE:'defaultShelfLifeDays'};
function InventoryStaffChangeRequests(){
 const addButton=useRef<HTMLButtonElement>(null); const detailTrigger=useRef<HTMLElement>(null);
 const [items,setItems]=useState<ChangeRequest[]|null>(null),[total,setTotal]=useState(0),[summary,setSummary]=useState<{totalRequests:number;approved:number;pending:number;rejected:number}|null>(null),[ingredients,setIngredients]=useState<ChangeRequestIngredientOption[]>([]),[recordsFailed,setRecordsFailed]=useState(false),[summaryFailed,setSummaryFailed]=useState(false);
 const [search,setSearch]=useState(''),[type,setType]=useState(''),[status,setStatus]=useState(''),[range,setRange]=useState<(typeof DATE_RANGES)[number]>('All dates'),[from,setFrom]=useState(''),[to,setTo]=useState(''),[page,setPage]=useState(1),[rows,setRows]=useState(10),[open,setOpen]=useState(false),[detail,setDetail]=useState<ChangeRequest|null>(null);
 const [draft,setDraft]=useState<{requestType:ChangeRequestType|'';ingredientId:string;requestedValue:string;reason:string}>({requestType:'',ingredientId:'',requestedValue:'',reason:''}),[errors,setErrors]=useState<Record<string,string>>({}),[touched,setTouched]=useState<Record<string,boolean>>({}),[submitted,setSubmitted]=useState(false),[busy,setBusy]=useState(false);
 const period=datesFor(range,from,to);
 const loadRecords=(signal?:AbortSignal)=>listChangeRequests({page,pageSize:rows,search:search.trim()||undefined,type:(type||undefined) as ChangeRequestType|undefined,status:(status||undefined) as ChangeRequestStatus|undefined,...period,currentOnly:true},signal).then(records=>{setItems(records.items);setTotal(records.total);setRecordsFailed(false)}).catch(e=>{if((e as Error).name!=='AbortError'){setItems(null);setRecordsFailed(true)}});
 const loadSummary=(signal?:AbortSignal)=>getChangeRequestSummary(signal).then(nextSummary=>{setSummary(nextSummary);setSummaryFailed(false)}).catch(e=>{if((e as Error).name!=='AbortError')setSummaryFailed(true)});
 useEffect(()=>{const controller=new AbortController(),timer=window.setTimeout(()=>void loadRecords(controller.signal),200);return()=>{window.clearTimeout(timer);controller.abort()}},[search,type,status,range,from,to,page,rows]);
 useEffect(()=>{const controller=new AbortController();void loadSummary(controller.signal);return()=>controller.abort()},[]);
 useEffect(()=>{const controller=new AbortController();listChangeRequestIngredients(controller.signal).then(result=>setIngredients(result.ingredients)).catch(()=>setIngredients([]));return()=>controller.abort()},[]);
 const selected=ingredients.find(item=>item.id===draft.ingredientId), field=draft.requestType?fieldByType[draft.requestType]:undefined, current=selected&&field?String(selected[field]??'—'):'—';
 const validate=()=>{const next:Record<string,string>={};if(!draft.requestType)next.requestType='Select a request type.';if(!draft.ingredientId)next.ingredientId='Select an ingredient.';if(!draft.requestedValue.trim())next.requestedValue='Enter the requested value.';else if(draft.requestType&&['MINIMUM_STOCK_CHANGE','STANDARD_UNIT_COST_CHANGE','DEFAULT_SHELF_LIFE_CHANGE'].includes(draft.requestType)&&(!Number.isFinite(Number(draft.requestedValue))||Number(draft.requestedValue)<0))next.requestedValue='Enter a valid value.';if(!draft.reason.trim())next.reason='Enter a reason.';return next};
 const submit=async(e:FormEvent)=>{e.preventDefault();setSubmitted(true);const next=validate();setErrors(next);if(Object.keys(next).length)return;setBusy(true);try{const numeric=['MINIMUM_STOCK_CHANGE','STANDARD_UNIT_COST_CHANGE','DEFAULT_SHELF_LIFE_CHANGE'].includes(draft.requestType);await createChangeRequest({requestType:draft.requestType as ChangeRequestType,ingredientId:draft.ingredientId,requestedValue:numeric?Number(draft.requestedValue):draft.requestedValue.trim(),reason:draft.reason.trim()});setOpen(false);setDraft({requestType:'',ingredientId:'',requestedValue:'',reason:''});setTouched({});setSubmitted(false);await Promise.all([loadRecords(),loadSummary()])}finally{setBusy(false)}};
 const show=(name:string)=>Boolean(errors[name]&&(submitted||touched[name])); const input=(name:keyof typeof draft,value:string)=>{setDraft(v=>({...v,[name]:value}));setErrors(validate())};
 const filtered=Boolean(search||type||status||range!=='All dates'||from||to); const reset=()=>{setSearch('');setType('');setStatus('');setRange('All dates');setFrom('');setTo('');setPage(1)};
 const requestedChange=(record:ChangeRequest)=>`${record.targetField?CHANGE_REQUEST_TARGET_LABELS[record.targetField]:'Requested Change'}: ${formatStaffChangeRequestValue(record,record.currentValue)} → ${formatStaffChangeRequestValue(record,record.requestedValue)}`;
 const kpis=[[FileInput,'brand','Total Requests',summary?.totalRequests,'Your submitted requests'],[Clock3,'info','Pending',summary?.pending,'Awaiting manager review'],[CheckCircle2,'attention','Approved',summary?.approved,'Approved requests'],[XCircle,'critical','Rejected',summary?.rejected,'Rejected requests']] as const;
 return <><PageHeader eyebrow="Follow-up" title="My Requests" description="Submit and track your ingredient change requests."/>
 <div className="sl-admin-view sl-staff-usage-v150 sl-staff-requests-v162 sl-staff-my-requests"><div className="sl-superadmin-dashboard-v49 sl-staff-usage-v150"><section className="sl-sa-kpis sl-inventory-staff-kpis sl-staff-usage-kpis sl-superadmin-dashboard-kpis-v201">{kpis.map(([Icon,tone,label,value,helper])=><article className="sl-sa-kpi sl-inventory-staff-kpi" data-tone={tone} key={label}><span className="sl-sa-kpi-icon"><Icon/></span><div><span>{label}</span><strong>{summaryFailed||summary===null?'—':value}</strong><small>{summaryFailed?'Request data unavailable':summary===null?'Loading request summary':helper}</small></div></article>)}</section></div>
 <section className="sl-application-records sl-sa-ingredients-table-card sl-staff-usage-card sl-staff-usage-records sl-sa-account-pattern-records sl-staff-my-requests-records"><header className="sl-application-records-header sl-staff-usage-card-head sl-staff-usage-records-head"><span className="sl-staff-usage-head-icon"><FileInput/></span><h2>Change Request Records</h2></header><div className="sl-sa-ingredients-table-filters"><div className="sl-sa-ingredients-filter-card sl-staff-requests-toolbar"><label className="sl-sa-ingredients-search"><span>Search records</span><div><Search size={17}/><input value={search} placeholder="Search by request ID or ingredient..." onChange={e=>{setSearch(e.target.value);setPage(1)}}/></div></label><label><span>Type</span><select value={type} onChange={e=>{setType(e.target.value);setPage(1)}}><option value="">All Types</option>{CHANGE_REQUEST_TYPES.map(value=><option value={value} key={value}>{CHANGE_REQUEST_TYPE_LABELS[value]}</option>)}</select></label><label><span>Status</span><select value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}}><option value="">All Statuses</option><option value="PENDING">Pending</option><option value="APPROVED">Approved</option><option value="REJECTED">Rejected</option></select></label><label><span>Date Range</span><select value={range} onChange={e=>{setRange(e.target.value as typeof range);setPage(1)}}>{DATE_RANGES.map(value=><option key={value}>{value}</option>)}</select></label>{range==='Custom range'&&<div className="sl-v219-custom-date-range"><label><span>From</span><input type="date" value={from} max={to||undefined} onChange={e=>{setFrom(e.target.value);setPage(1)}}/></label><label><span>To</span><input type="date" value={to} min={from||undefined} onChange={e=>{setTo(e.target.value);setPage(1)}}/></label></div>}<div className="sl-sa-ingredients-filter-actions"><button type="button" className="sl-button" onClick={reset}>Reset</button><button ref={addButton} className="sl-button sl-button-primary" type="button" onClick={()=>{setDraft({requestType:'',ingredientId:'',requestedValue:'',reason:''});setErrors({});setTouched({});setSubmitted(false);setOpen(true)}}><Plus size={16}/>New Request</button></div></div></div>
 <div className="sl-sa-ingredients-table-scroll sl-staff-usage-table-shell"><table className="sl-records-table sl-sa-ingredients-table sl-data-table sl-staff-my-requests-table"><colgroup><col className="sl-staff-request-col-standard"/><col className="sl-staff-request-col-standard"/><col className="sl-staff-request-col-change"/><col className="sl-staff-request-col-standard"/><col className="sl-staff-request-col-status"/></colgroup><thead><tr>{['Request ID','Ingredient','Requested Change','Submitted On','Status'].map(v=><th key={v}>{v}</th>)}</tr></thead><tbody>{items?.length?items.map(record=><tr key={record.id} className="sl-detail-enabled-row" tabIndex={0} onClick={e=>{detailTrigger.current=e.currentTarget;setDetail(record)}} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();detailTrigger.current=e.currentTarget;setDetail(record)}}}><td><span className="sl-canonical-identifier">{record.requestID}</span></td><td className="sl-emphasized-value">{record.ingredient?.name??'—'}</td><td><span className="sl-staff-request-change-summary" title={requestedChange(record)}>{requestedChange(record)}</span></td><td>{formatDateTime(record.createdAt)}</td><td><Status tone={record.status==='APPROVED'?'success':record.status==='REJECTED'?'critical':'attention'}>{record.status==='PENDING'?'Pending':record.status==='APPROVED'?'Approved':'Rejected'}</Status></td></tr>):<tr><td colSpan={5} className="sl-empty-cell"><DataState kind={recordsFailed?'error':items===null?'loading':'empty'} title={recordsFailed?'Data unavailable':items===null?'Loading requests':filtered?'No matching records':'No requests yet'} description={recordsFailed?'The request service could not be reached.':filtered?'Try adjusting your search or filters.':'Your submitted change requests will appear here.'}/></td></tr>}</tbody></table></div><footer className="sl-application-records-footer sl-sa-ingredients-footer"><label>Rows per page <select value={rows} onChange={e=>{setRows(Number(e.target.value));setPage(1)}}>{PAGE_SIZES.map(v=><option key={v}>{v}</option>)}</select></label><Pagination compact page={page} pageSize={rows} total={total} itemLabel={total===1?'request':'requests'} onPageChange={setPage}/></footer></section></div>
 <InventoryStaffModal open={open} title="New Change Request" subtitle="Describe the ingredient master-data change that needs review." Icon={FileInput} onDismiss={()=>setOpen(false)} returnFocus={addButton} showClose={false} busy={busy} className={`sl-staff-my-request-dialog${draft.requestType ? '' : ' sl-staff-my-request-dialog--initial'}`}><InventoryStaffModalForm formId="new-change-request" onSubmit={submit} secondaryLabel="Cancel" onSecondary={()=>setOpen(false)} primaryLabel="Submit Request" busy={busy} className="sl-staff-my-request-form"><div className="sl-staff-my-request-form-grid"><label className={!draft.requestType?'sl-staff-my-request-full':undefined}><span>Request Type</span><select value={draft.requestType} onBlur={()=>setTouched(v=>({...v,requestType:true}))} onChange={e=>{setDraft(v=>({...v,requestType:e.target.value as ChangeRequestType,requestedValue:''}));setErrors({})}}><option value="">Select request type</option>{CHANGE_REQUEST_TYPES.map(v=><option key={v} value={v}>{CHANGE_REQUEST_TYPE_LABELS[v]}</option>)}</select>{show('requestType')&&<span className="sl-field-error">{errors.requestType}</span>}</label>{draft.requestType&&<><label><span>Ingredient</span><select value={draft.ingredientId} onBlur={()=>setTouched(v=>({...v,ingredientId:true}))} onChange={e=>input('ingredientId',e.target.value)}><option value="">Select ingredient</option>{ingredients.map(v=><option value={v.id} key={v.id}>{v.name}</option>)}</select>{show('ingredientId')&&<span className="sl-field-error">{errors.ingredientId}</span>}</label><label><span>Current Value</span><output className="sl-staff-my-request-derived">{current}</output></label><label><span>{field?CHANGE_REQUEST_TARGET_LABELS[field as keyof typeof CHANGE_REQUEST_TARGET_LABELS]:'Requested Value'}</span>{draft.requestType==='CATEGORY_CHANGE'?<select value={draft.requestedValue} onChange={e=>input('requestedValue',e.target.value)}><option value="">Select category</option>{CATEGORIES.map(v=><option key={v}>{v}</option>)}</select>:draft.requestType==='UNIT_OF_MEASURE_CHANGE'?<select value={draft.requestedValue} onChange={e=>input('requestedValue',e.target.value)}><option value="">Select unit</option>{CHANGE_REQUEST_UNITS.map(v=><option key={v}>{v}</option>)}</select>:<input value={draft.requestedValue} inputMode={draft.requestType&&['MINIMUM_STOCK_CHANGE','STANDARD_UNIT_COST_CHANGE','DEFAULT_SHELF_LIFE_CHANGE'].includes(draft.requestType)?'decimal':undefined} onBlur={()=>setTouched(v=>({...v,requestedValue:true}))} onChange={e=>input('requestedValue',e.target.value)}/>} {show('requestedValue')&&<span className="sl-field-error">{errors.requestedValue}</span>}</label><label className="sl-staff-my-request-full"><span>Reason</span><textarea value={draft.reason} onBlur={()=>setTouched(v=>({...v,reason:true}))} onChange={e=>input('reason',e.target.value)}/>{show('reason')&&<span className="sl-field-error">{errors.reason}</span>}</label></>}</div></InventoryStaffModalForm></InventoryStaffModal>
 <ChangeRequestDetailsDialog inventoryStaff request={detail} onDismiss={()=>setDetail(null)} returnFocus={detailTrigger}/></>;
}

export default function ChangeRequests() {
 const { user } = useApplicationWorkspace();
 return user.role === 'Manager' ? <ConnectedManagerChangeRequestsPage /> : <InventoryStaffChangeRequests />;
}
