import type { Mongoose } from 'mongoose';
import { AdministrationError, forbidden } from '../middleware/administration.middleware';
import type { Actor } from './administration';
import type { ChangeRequestInput } from '../validators/change-request';

const label = (type: string) => type.split('_').map(word => word[0] + word.slice(1).toLowerCase()).join(' ');
export function createChangeRequests(driver: Mongoose, requests: any, counters: any, ingredients: any, batches: any, users: any, audits: any) {
  const name = (user: any) => user?.name?.trim() || `${user?.firstName ?? ''} ${user?.lastName ?? ''}`.trim() || 'Unknown account';
  const view = async (row: any) => { const [ingredient,batch,requester,reviewer] = await Promise.all([row.ingredientId?ingredients.findById(row.ingredientId).select('_id name').lean().exec():null,row.batchId?batches.findById(row.batchId).select('_id batchID ingredientId').lean().exec():null,users.findById(row.requestedBy).select('_id name firstName lastName').lean().exec(),row.reviewedBy?users.findById(row.reviewedBy).select('_id name firstName lastName').lean().exec():null]); return { id:row._id.toString(),requestID:row.requestID,requestType:row.requestType,ingredient:ingredient?{id:ingredient._id.toString(),name:ingredient.name}:undefined,batch:batch?{id:batch._id.toString(),batchID:batch.batchID}:undefined,reason:row.reason,currentValue:row.currentValue,requestedValue:row.requestedValue,requestedQuantity:row.requestedQuantity,requestedUnit:row.requestedUnit,requestDescription:row.requestDescription,proposedBatch:row.proposedBatch?{dateReceived:row.proposedBatch.dateReceived?.toISOString(),quantityReceived:row.proposedBatch.quantityReceived,expirationDate:row.proposedBatch.expirationDate?.toISOString(),unitCost:row.proposedBatch.unitCost}:undefined,targetField:row.targetField,status:row.status,requestedBy:{id:requester._id.toString(),name:name(requester)},reviewedBy:reviewer?{id:reviewer._id.toString(),name:name(reviewer)}:undefined,reviewedAt:row.reviewedAt?.toISOString(),reviewNote:row.reviewNote,createdAt:row.createdAt.toISOString(),updatedAt:row.updatedAt.toISOString() }; };
  const assertRelations = async (input: ChangeRequestInput) => { if(input.ingredientId && !await ingredients.exists({_id:input.ingredientId})) throw new AdministrationError(404,'NOT_FOUND','Ingredient not found'); if(input.batchId){const batch=await batches.findById(input.batchId).select('ingredientId').lean().exec();if(!batch)throw new AdministrationError(404,'NOT_FOUND','Inventory batch not found');if(input.ingredientId&&batch.ingredientId.toString()!==input.ingredientId)throw new AdministrationError(400,'VALIDATION_ERROR','Check the supplied fields',[{field:'batchId',message:'Selected batch does not belong to the ingredient'}]);} };
  return {
    async list(actor: Actor, query: any) { const filter:any={}; if(actor.role==='Inventory Staff')filter.requestedBy=actor.id; else if(actor.role!=='Manager'&&actor.role!=='Super Admin')throw forbidden(); if(query.type)filter.requestType=query.type;if(query.status)filter.status=query.status;if(query.from||query.to)filter.createdAt={...(query.from?{$gte:query.from}:{}),...(query.to?{$lte:query.to}:{})}; if(query.search){const rows=await requests.find(filter).sort({createdAt:-1,_id:-1}).populate('ingredientId','name').populate('batchId','batchID').lean().exec();const term=query.search.toLowerCase();const items=rows.filter((row:any)=>[row.requestID,row.ingredientId?.name,row.batchId?.batchID].some(value=>value?.toLowerCase().includes(term)));return {items:await Promise.all(items.slice((query.page-1)*query.pageSize,query.page*query.pageSize).map(view)),page:query.page,pageSize:query.pageSize,total:items.length};} const total=await requests.countDocuments(filter);const rows=await requests.find(filter).sort({createdAt:-1,_id:-1}).skip((query.page-1)*query.pageSize).limit(query.pageSize).lean().exec();return {items:await Promise.all(rows.map(view)),page:query.page,pageSize:query.pageSize,total}; },
    async detail(actor: Actor,id:string){const row=await requests.findById(id).lean().exec();if(!row||(actor.role==='Inventory Staff'&&row.requestedBy.toString()!==actor.id)||!['Inventory Staff','Manager','Super Admin'].includes(actor.role))throw new AdministrationError(404,'NOT_FOUND','Change request not found');return view(row);},
    async summary(actor:Actor){if(actor.role!=='Inventory Staff')throw forbidden();const counts=await requests.aggregate([{ $match:{requestedBy:new driver.Types.ObjectId(actor.id)} },{$group:{_id:'$status',count:{$sum:1}}}]);const map=new Map<string,number>(counts.map((row:any)=>[row._id,row.count]));return {totalRequests:[...map.values()].reduce((a,b)=>a+b,0),approved:map.get('APPROVED')??0,pending:map.get('PENDING')??0,rejected:map.get('REJECTED')??0};},
    async create(actor:Actor,input:ChangeRequestInput){if(actor.role!=='Inventory Staff')throw forbidden();await assertRelations(input);const ingredient=input.ingredientId?await ingredients.findById(input.ingredientId).select('unitOfMeasure').lean().exec():null;const batch=input.batchId?await batches.findById(input.batchId).select('quantity unit dateReceived expirationDate unitCost ingredientId').lean().exec():null;const derived:any={...input};if(input.requestType==='QUANTITY_ADJUSTMENT'&&batch){derived.currentValue=`${batch.quantity} ${batch.unit}`;}if(input.requestType==='UNIT_CORRECTION'&&ingredient){derived.currentValue=ingredient.unitOfMeasure;}if(input.requestType==='BATCH_CORRECTION'&&batch){derived.currentValue=String(batch[input.targetField as keyof typeof batch] ?? '');}if(input.requestType==='ADD_MISSING_BATCH'&&ingredient){derived.currentValue=ingredient.unitOfMeasure;}return driver.connection.transaction(async(session:any)=>{const now=new Date(),dateKey=`${now.getUTCFullYear()}${String(now.getUTCMonth()+1).padStart(2,'0')}${String(now.getUTCDate()).padStart(2,'0')}`;const counter=await counters.findOneAndUpdate({dateKey},{$inc:{sequence:1}},{new:true,upsert:true,setDefaultsOnInsert:true,session}).lean().exec();const requestID=`REQ-${dateKey}-${String(counter.sequence).padStart(3,'0')}`;const created=await requests.create([{...derived,requestID,status:'PENDING',requestedBy:new driver.Types.ObjectId(actor.id)}],{session});const row=created[0];await audits.create([{userId:actor.id,actorName:actor.name?.trim()||'Unknown account',actorRole:actor.role,action:'CREATE',targetType:'ChangeRequest',targetId:row._id.toString(),targetName:requestID,module:'Change Requests',status:'Success',details:`${label(input.requestType)} submitted`}],{session});return view(row);});},
    async review(actor:Actor,id:string,status:'APPROVED'|'REJECTED',reviewNote?:string){if(actor.role!=='Manager')throw forbidden();return driver.connection.transaction(async(session:any)=>{const row=await requests.findOneAndUpdate({_id:id,status:'PENDING'},{$set:{status,reviewedBy:new driver.Types.ObjectId(actor.id),reviewedAt:new Date(),...(reviewNote?{reviewNote}:{})}},{new:true,session}).lean().exec();if(!row)throw new AdministrationError(409,'CONFLICT','This change request has already been reviewed');await audits.create([{userId:actor.id,actorName:actor.name?.trim()||'Unknown account',actorRole:actor.role,action:'UPDATE',targetType:'ChangeRequest',targetId:id,targetName:row.requestID,module:'Change Requests',status:'Success',details:`${status==='APPROVED'?'Approved':'Rejected'} ${label(row.requestType)}`}],{session});return view(row);});},
  };
}
