const { test } = require('node:test');
const assert = require('node:assert/strict');
const { createServer } = require('node:http');
const { once } = require('node:events');
const { randomBytes } = require('node:crypto');
const { createApp } = require('../dist/app');
const { createAuth } = require('../dist/services/auth');
const { changeRequestInput, changeRequestPeriodQuery, changeRequestQuery, reviewInput } = require('../dist/validators/change-request');
const ingredient='4'.repeat(24);
test('accepts every approved Ingredient master-data target and derives the target field',()=>{
 const cases=[['MINIMUM_STOCK_CHANGE',5,'minimumStock'],['STANDARD_UNIT_COST_CHANGE',0,'standardUnitCost'],['CATEGORY_CHANGE','Meat','category'],['BRAND_CHANGE','Local','brand'],['DESCRIPTION_CHANGE','Fresh cut','description'],['UNIT_OF_MEASURE_CHANGE','kg','unitOfMeasure'],['DEFAULT_SHELF_LIFE_CHANGE',30,'defaultShelfLifeDays']];
 for(const [requestType,requestedValue,targetField] of cases)assert.equal(changeRequestInput({requestType,ingredientId:ingredient,requestedValue,reason:'Correct master data'}).targetField,targetField);
});
test('rejects legacy types, unknown/server-owned fields, malformed values and invalid filters',()=>{
 for(const body of [{requestType:'QUANTITY_ADJUSTMENT',ingredientId:ingredient,requestedValue:2,reason:'x'},{requestType:'CATEGORY_CHANGE',ingredientId:ingredient,requestedValue:'Unknown',reason:'x'},{requestType:'UNIT_OF_MEASURE_CHANGE',ingredientId:ingredient,requestedValue:'bucket',reason:'x'},{requestType:'MINIMUM_STOCK_CHANGE',ingredientId:ingredient,requestedValue:Infinity,reason:'x'},{requestType:'BRAND_CHANGE',ingredientId:ingredient,requestedValue:'Brand',reason:'x',status:'APPROVED'}])assert.throws(()=>changeRequestInput(body));
 assert.throws(()=>changeRequestQuery({page:1,pageSize:5})); assert.throws(()=>changeRequestQuery({page:1,pageSize:10,currentOnly:'false'})); assert.equal(changeRequestQuery({page:1,pageSize:10,currentOnly:'true'}).currentOnly,true); assert.throws(()=>reviewInput({reviewNote:'  '},true));
 const sameDay=changeRequestQuery({page:1,pageSize:10,from:'2026-10-02',to:'2026-10-02'}); assert.equal(sameDay.from.toISOString(),'2026-10-02T00:00:00.000Z'); assert.equal(sameDay.to.toISOString(),'2026-10-03T00:00:00.000Z'); assert.throws(()=>changeRequestQuery({page:1,pageSize:10,to:'2026-10-02T12:00:00Z'}));
 const period=changeRequestPeriodQuery({from:'2026-10-02',to:'2026-10-02'}); assert.equal(period.to.toISOString(),'2026-10-03T00:00:00.000Z'); assert.throws(()=>changeRequestPeriodQuery({page:'1'}));
});
test('Change Request routes enforce Staff creation and Manager review',async()=>{
 const staff={id:'1'.repeat(24),_id:'1'.repeat(24),name:'Staff',email:'staff@shelflife.com',role:'Inventory Staff',isActive:true,authVersion:0},manager={...staff,id:'2'.repeat(24),_id:'2'.repeat(24),name:'Manager',email:'manager@shelflife.com',role:'Manager'};let created;
 const service={summary:async()=>({totalRequests:0,approved:0,pending:0,rejected:0}),managerSummary:async(_actor,period)=>({totalRequests:period.from?1:0,approved:0,pending:1,rejected:0}),ingredientOptions:async()=>({ingredients:[{id:ingredient,name:'Chicken Breast',minimumStock:2,category:'Meat',brand:'',description:'',unitOfMeasure:'kg'}]}),list:async(_a,q)=>({items:[],page:q.page,pageSize:q.pageSize,total:0}),detail:async()=>({id:'5'.repeat(24)}),create:async(actor,input)=>(created={actor,input},{id:'5'.repeat(24)}),review:async()=>({id:'5'.repeat(24),status:'APPROVED'})};
 const auth=createAuth({byId:async id=>[staff,manager].find(user=>user.id===id)||null,byEmail:async()=>null},randomBytes(48).toString('hex')),app=createApp([],()=>true,auth,undefined,undefined,undefined,undefined,undefined,undefined,service),http=createServer(app);http.listen(0,'127.0.0.1');await once(http,'listening');const base=`http://127.0.0.1:${http.address().port}/api/change-requests`,request=(user,path='',method='GET',body)=>fetch(base+path,{method,headers:{Authorization:`Bearer ${auth.issue(user).accessToken}`,...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});
 try{assert.equal((await request(manager,'?page=1&pageSize=10&currentOnly=true')).status,200);assert.equal((await request(manager,'/manager-summary?from=2026-10-02&to=2026-10-02')).status,200);assert.equal((await request(staff,'/manager-summary')).status,403);assert.equal((await request(staff,'/ingredient-options')).status,200);assert.equal((await request(manager,'/ingredient-options')).status,200);assert.equal((await request(staff,'/summary')).status,200);assert.equal((await request(manager,'/summary')).status,403);assert.equal((await request(manager,'','POST',{requestType:'CATEGORY_CHANGE',ingredientId:ingredient,requestedValue:'Meat',reason:'Correct'})).status,403);assert.equal((await request(staff,'','POST',{requestType:'CATEGORY_CHANGE',ingredientId:ingredient,requestedValue:'Meat',reason:'Correct'})).status,201);assert.equal(created.input.targetField,'category');assert.equal((await request(staff,'/'+'5'.repeat(24)+'/approve','POST',{})).status,403);assert.equal((await request(manager,'/'+'5'.repeat(24)+'/approve','POST',{})).status,200)}finally{http.closeAllConnections();await new Promise(resolve=>http.close(resolve))}
});
