const { test } = require('node:test');
const assert = require('node:assert/strict');
const { createServer } = require('node:http');
const { once } = require('node:events');
const { randomBytes, randomUUID } = require('node:crypto');
const { Mongoose } = require('mongoose');
const { createApp } = require('../dist/app');
const { createAuth } = require('../dist/services/auth');
const { ingredientModel } = require('../dist/models/ingredient');
const { inventoryBatchModel, provisionBatchIndexes } = require('../dist/models/inventory-batch');
const { auditRecordModel } = require('../dist/models/audit-record');
const { systemConfigModel } = require('../dist/models/system-config');
const { createSystemConfig } = require('../dist/services/system-config');
const { createInventoryBatches } = require('../dist/services/inventory-batches');

test('MongoDB batch API preserves decimals, FEFO, live status, permissions, versions, quantity integrity and atomic auditing', { skip: process.env.RUN_MONGO_HARDENING_TESTS !== 'true' }, async () => {
  const driver = new Mongoose(), prefix = `batch_test_${randomUUID().replaceAll('-', '')}_`, models = [];
  let server;
  const isolated = factory => { const base = factory(driver); const model = driver.model(`Test${base.modelName}`, base.schema.clone(), prefix + base.collection.name); models.push(model); return model; };
  try {
    await driver.connect(process.env.MONGO_URI, { dbName: 'shelflifeai', autoIndex: false, autoCreate: false, serverSelectionTimeoutMS: 5000 });
    const ingredients = isolated(ingredientModel), batches = isolated(inventoryBatchModel), audits = isolated(auditRecordModel), configs = isolated(systemConfigModel);
    for (const model of models) await model.createCollection();
    await provisionBatchIndexes(batches); await provisionBatchIndexes(batches);
    const identity = (await batches.collection.listIndexes().toArray()).find(index => index.name === 'ingredient_batch_code_unique');
    assert.equal(identity.unique, true); assert.equal(identity.partialFilterExpression, undefined);
    const roles = ['Super Admin', 'Admin', 'Inventory Manager', 'Inventory Staff'];
    const users = roles.map((role, i) => ({ id: String(i + 1).repeat(24), _id: String(i + 1).repeat(24), email: `batch${i}@shelflife.com`, role, isActive: true }));
    const manager = users[2], config = createSystemConfig(driver, configs, audits);
    let clock = new Date('2026-09-21T15:59:59Z');
    const service = createInventoryBatches(driver, batches, ingredients, audits, config, () => clock);
    const auth = createAuth({ byId: async id => users.find(user => user.id === id), byEmail: async () => null }, randomBytes(48).toString('hex'));
    server = createServer(createApp([], () => true, auth, undefined, undefined, undefined, config, service));
    server.listen(0, '127.0.0.1'); await once(server, 'listening');
    const base = `http://127.0.0.1:${server.address().port}/api/inventory-batches`;
    const request = (user, method = 'GET', path = '', body) => fetch(base + path, { method, headers: { ...(user ? { Authorization: `Bearer ${auth.issue(user).accessToken}` } : {}), 'Content-Type': 'application/json' }, ...(body === undefined ? {} : { body: typeof body === 'string' ? body : JSON.stringify(body) }) });
    const parent = await ingredients.create({ name: 'Batch fixture', category: 'Other', unitOfMeasure: 'kg', createdBy: manager.id });
    const input = { ingredientId: parent.id, batchCode: 'B-1', initialQuantity: '10.123', unit: 'kg', unitCost: '100.1234', dateReceived: '2026-09-20', expirationDate: '2026-09-29' };
    assert.equal((await request(null)).status, 401);
    for (const user of users) {
      assert.equal((await request(user)).status, 200);
      if (user.role === 'Inventory Manager') continue;
      for (const [method, path] of [['POST', ''], ['PATCH', '/' + '1'.repeat(24)], ['DELETE', '/' + '1'.repeat(24)], ['POST', '/' + '1'.repeat(24) + '/quantity-corrections']]) assert.equal((await request(user, method, path, '{bad-json')).status, 403);
    }
    assert.equal((await request(manager, 'POST', '', { ...input, quantity: '1' })).status, 400);
    let http = await request(manager, 'POST', '', input); assert.equal(http.status, 201);
    let batch = (await http.json()).batch;
    assert.equal(batch.quantity, input.initialQuantity); assert.equal(batch.initialQuantity, input.initialQuantity); assert.equal(batch.unitCost, input.unitCost); assert.equal(batch.currency, 'PHP'); assert.equal(batch.version, 0); assert.equal(batch.status, 'Normal'); assert.equal(batch._id, undefined);
    const id = batch.id, rawBefore = await batches.collection.findOne({ _id: new driver.Types.ObjectId(id) });
    assert.equal(rawBefore.quantity._bsontype, 'Decimal128'); assert.equal(rawBefore.status, undefined);
    clock = new Date('2026-09-28T16:00:00Z');
    assert.equal((await service.get(id)).status, 'Critical');
    clock = new Date('2026-09-29T16:00:00Z');
    assert.equal((await service.get(id)).status, 'Expired');
    clock = new Date('2026-09-21T15:59:59Z');
    await config.patch(users[0].id, { expectedVersion: 0, approachingDays: 10 });
    assert.equal((await service.get(id)).status, 'Approaching Expiry');
    const rawAfter = await batches.collection.findOne({ _id: rawBefore._id });
    assert.equal(rawAfter.updatedAt.getTime(), rawBefore.updatedAt.getTime()); assert.equal(rawAfter.version, 0); assert.equal(rawAfter.status, undefined);
    for (const patch of [{ quantity: '5.000' }, { initialQuantity: '12.000' }, { version: 100 }, { isActive: false }, { ingredientId: '1'.repeat(24) }]) assert.equal((await request(manager, 'PATCH', `/${id}`, { expectedVersion: 0, ...patch })).status, 400);
    assert.equal((await request(manager, 'PATCH', `/${id}`, { unitCost: '2' })).status, 400);
    http = await request(manager, 'PATCH', `/${id}`, { expectedVersion: 0, unitCost: '99.9999' }); assert.equal(http.status, 200);
    batch = (await http.json()).batch; assert.equal(batch.version, 1); assert.equal(batch.quantity, '10.123');
    assert.equal((await request(manager, 'PATCH', `/${id}`, { expectedVersion: 0, unitCost: '1' })).status, 409);
    assert.equal((await request(manager, 'DELETE', `/${id}`, { expectedVersion: 0 })).status, 409);
    const correction = { expectedVersion: 1, correctedQuantity: '10.124', approved: true, reason: 'Manager count correction' };
    assert.equal((await request(manager, 'POST', `/${id}/quantity-corrections`, correction)).status, 400);
    assert.equal((await request(manager, 'POST', `/${id}/quantity-corrections`, { ...correction, correctedQuantity: '1', approved: false })).status, 400);
    http = await request(manager, 'POST', `/${id}/quantity-corrections`, { ...correction, correctedQuantity: '0' }); assert.equal(http.status, 200);
    batch = (await http.json()).batch; assert.equal(batch.quantity, '0.000'); assert.equal(batch.initialQuantity, '10.123'); assert.equal(batch.version, 2);
    const correctionAudit = await audits.findOne({ targetId: id, reason: correction.reason }).lean();
    assert.equal(correctionAudit.oldValue.quantity, '10.123'); assert.equal(correctionAudit.newValue.quantity, '0.000'); assert.equal(correctionAudit.newValue.version, 2);
    assert.equal((await service.correctQuantity(manager, id, { ...correction, expectedVersion: 2, correctedQuantity: '10.123' })).version, 3);
    const race = await Promise.allSettled([service.patch(manager, id, { expectedVersion: 3, unitCost: '1' }), service.correctQuantity(manager, id, { ...correction, expectedVersion: 3, correctedQuantity: '9.123' })]);
    assert.equal(race.filter(result => result.status === 'fulfilled').length, 1);
    assert.equal(race.find(result => result.status === 'rejected').reason.status, 409);
    assert.equal(await audits.countDocuments({ targetId: id }), 5);
    const failAudits = { create: async () => { throw new Error('audit failure'); } };
    const failing = createInventoryBatches(driver, batches, ingredients, failAudits, config, () => clock);
    const retained = await service.get(id), auditCount = await audits.countDocuments();
    await assert.rejects(failing.create(manager, { ...input, batchCode: 'rollback' }), /audit failure/);
    await assert.rejects(failing.patch(manager, id, { expectedVersion: 4, unitCost: '5' }), /audit failure/);
    await assert.rejects(failing.correctQuantity(manager, id, { ...correction, expectedVersion: 4, correctedQuantity: '1' }), /audit failure/);
    await assert.rejects(failing.archive(manager, id, { expectedVersion: 4 }), /audit failure/);
    assert.deepEqual(await service.get(id), retained); assert.equal(await audits.countDocuments(), auditCount);
    assert.equal(await batches.countDocuments({ batchCode: 'rollback' }), 0);
    await batches.findByIdAndUpdate(id, { $set: { initialQuantity: '999.000' } }, { runValidators: true });
    assert.equal((await service.get(id)).initialQuantity, '10.123');
    assert.equal((await request(manager, 'DELETE', `/${id}`, { expectedVersion: 4 })).status, 204);
    const archived = await batches.collection.findOne({ _id: rawBefore._id });
    assert.equal(archived.isActive, false); assert.equal(archived.version, 5);
    assert.equal((await service.list({})).total, 0); assert.equal((await service.list({ includeArchived: 'true' })).total, 1);
    assert.equal((await service.get(id)).isActive, false);
    assert.equal((await request(manager, 'POST', '', input)).status, 409);
    await assert.rejects(service.correctQuantity(manager, id, { ...correction, expectedVersion: 5, correctedQuantity: '1' }), e => e.status === 404);
    const secondParent = await ingredients.create({ name: 'Second fixture', category: 'Other', unitOfMeasure: 'kg', createdBy: manager.id });
    const sameCode = await service.create(manager, { ...input, ingredientId: secondParent.id }); assert.equal(sameCode.batchCode, input.batchCode);
    await ingredients.updateOne({ _id: parent._id }, { $set: { isActive: false } });
    await assert.rejects(service.create(manager, { ...input, batchCode: 'inactive' }), e => e.status === 404);
    const fixtures = [];
    for (const [batchCode, dateReceived, expirationDate] of [['later', '2026-09-20', '2026-10-01'], ['tieA', '2026-09-19', '2026-09-28'], ['tieB', '2026-09-19', '2026-09-28'], ['receivedLater', '2026-09-20', '2026-09-28']]) fixtures.push(await service.create(manager, { ...input, ingredientId: secondParent.id, batchCode, dateReceived, expirationDate }));
    const page = await service.list({ ingredientId: secondParent.id, limit: '2' });
    assert.deepEqual(page.items.map(row => row.batchCode), ['tieA', 'tieB']);
    assert.ok(page.items[0].id < page.items[1].id); assert.equal(page.limit, 2); assert.equal(page.pageSize, undefined); assert.equal(page.total, 5);
    const next = await service.list({ ingredientId: secondParent.id, limit: '2', page: '2' });
    assert.deepEqual(next.items.map(row => row.batchCode), ['receivedLater', 'B-1']);
    console.log(JSON.stringify({ check: 'inventory-batch-contract', database: driver.connection.name, collection: batches.collection.name, decimal128: true, archiveRetained: true, dynamicStatus: true, fefo: true, optimisticConcurrency: true, transactionalAudit: true }));
  } finally {
    if (server) { server.closeAllConnections(); await new Promise(resolve => server.close(resolve)); }
    try { for (const model of models) { assert.ok(model.collection.name.startsWith(prefix)); await model.collection.drop(); } } finally { await driver.disconnect(); }
  }
});
